### ISSUE TITLE
My app can't be published Need your help

### ISSUE THREAD

**Issue by richard457** [YehudaKremer/msix#102]
# This might not be related to this package but I think this is the right place to get help
I am trying to submit my app to the windows store and I am getting these messages as feedback
```
App Policies: 10.1.2 Functionality

Notes To Developer

There is an issue with the functionality claimed in the metadata.
Functionality claimed in the metadata is not present in the product.
```
Can you guide me on how I can see or control the meta data information.?

**Comment by YehudaKremer** [comment]
Hello @richard457 

The only metadata that you setup with this package is the "capabilities",
select only the capabilities that you using, for example if you connecting to the web then use the `internetClient` capability.

Other then that, make sure in the [Microsoft Store dashboard](https://partner.microsoft.com/dashboard) that you fill up the **Properties**, **Age ratings**, **Store listings** and **Manage languages** pages with details about your app.
![image](https://user-images.githubusercontent.com/946652/154300450-1a166d13-2029-4f00-9383-e32e3029b19a.png)
