### ISSUE TITLE
Msix build failed [BUG] 

### ISSUE THREAD

**Issue by eb-so** [YehudaKremer/msix#104]
### :information_source: Info

**Version: `v3.2.1`**

### :speech_balloon: Description

```
Run flutter pub run msix:create
10

11
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 0% parsing cli arguments..        
12
✓ parsing cli arguments                                                           
13

14
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 7% validating config values..                             
15
✓ validating config values                                                           
16

17
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 15% cleaning temporary files..                                
18
✓ cleaning temporary files                                                           
19

20
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 23% creating app icons folder..                                
21
✓ creating app icons folder                                                           
22

23
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 30% copying app icons..                                 
24
✓ copying app icons                                                           
25

26
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 38% copying VC libraries..                         
27
✓ copying VC libraries                                                           
28

29
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 46% getting certificate publisher..                            
30
✓ getting certificate publisher                                                           
31

32
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 53% generate appx manifest..                                     
33
✓ generate appx manifest                                                           
34

35
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 61% generate package resource indexing files..                              
36
✓ generate package resource indexing files                                                           
37

38
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 69% packing..                                                
39
Microsoft (R) MakeAppx Tool
40

41
Copyright (C) 2013 Microsoft.  All rights reserved.
42

43

44

45
Option /v specified, switching to verbose output.
46

47
Option /o specified, existing files will be overwritten.
48

49
Using default hash method: SHA256.
50

51
The path (/p) parameter is: "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release\testsweets.msix"
52

53
The content directory (/d) parameter is: "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release"
54

55
Enumerating files from directory "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release"
56

57
Packing 130 file(s) in "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release" (content directory) to "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release\testsweets.msix" (output file name).
58

59
Memory limit defaulting to 3757860864 bytes.
60

61
Using "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release\AppxManifest.xml" as the manifest for the package.
62

63
MakeAppx : error: Failure at appxFactory->CreateManifestReader(manifestStream, &manifestReader) - 0x80080204 - The specified package format is not valid: The package manifest is not valid.
64

65
MakeAppx : error: Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Identity" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/@Publisher
66

67
'E=dane@filledstacks.com, CN=Dane Mackier, OU=FilledStacks Software, O=FilledStacks (Pty) Ltd, L=Cape Town,            S=Western Cape, C=ZA' violates pattern constraint of '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*'.
68

69
The attribute 'Publisher' with value 'E=dane@filledstacks.com, CN=Dane Mackier, OU=FilledStacks Software, O=FilledStacks (Pty) Ltd, L=Cape Town,            S=Western Cape, C=ZA' failed to parse.
70

71
Cleaning up output file "\\?\D:\a\sriptor\sriptor\src\application\build\windows\runner\Release\testsweets.msix".
72

73
MakeAppx : error: Failure at (CreatePackage( overwrite, hashAlgorithm, fileList, outputPath, manifestStream.Get(), forceCompressionNone, performanceOptions, encryptPackage, encryptionOptions, cgmPath, mainPackagePathForResourceExemption, makepriExeFullPath)) - 0x80080204 - The specified package format is not valid: The package manifest is not valid.
74

75
MakeAppx : error: Package creation failed.
76

77
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.
78

79

80
pub finished with exit code -1
81
Error: Process completed with exit code 1.
```
### :scroll: Pubspec.yaml

`name: testsweets
description: A tool to help advance the adoption of automatic quality assurance

# The following defines the version and build number for your Testsweets.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.6+1

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  get_it: ^7.1.3
  provider: ^6.0.1
  args: ^2.1.1
  async: ^2.6.1
  badges: ^2.0.1
  cupertino_icons: ^1.0.3
  flutter_custom_dialog: ^1.0.16
  freezed_annotation: ^1.1.0
  flutter_markdown: ^0.6.2
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  intl: ^0.17.0
  io: ^1.0.2
  logger: ^1.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  meta: ^1.3.0
  password_strength: ^0.2.0
  path: ^1.8.0
  path_provider: ^2.0.5
  archive: ^3.1.2
  shared_preferences: ^2.0.6
  uuid: ^3.0.4
  flutter_screenutil: ^5.0.0+2
  timeago: ^3.1.0
  page_transition: ^2.0.2
  bitsdojo_window: ^0.1.1+1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  equatable: ^2.0.3
  animations: ^2.0.0
  recase: ^4.0.0
  collection: ^1.15.0-nullsafety.4
  auto_size_text: ^3.0.0-nullsafety.0
  firedart: ^0.9.0+1
  file_picker: ^4.1.4
  filesystem_picker: ^1.0.3
  url_launcher: ^6.0.20
  file_selector:
    git:
      url: https://github.com/stuartmorgan/plugins.git
      ref: file-selector-macos
      path: packages/file_selector/file_selector

  file_selector_macos:
    git:
      url: https://github.com/stuartmorgan/plugins.git
      ref: file-selector-macos
      path: packages/file_selector/file_selector_macos

  # Local plugins
  device_finder:
    path: ../device_finder
  sweetcore:
    path: ../sweetcore

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  build_pubspec:
    git:
      url: https://github.com/FilledStacks/build_pubspec.git
      
  stacked_generator:
  build_runner: ^2.0.5
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  mockito: ^5.0.10
  msix: ^3.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

msix_config:
  display_name: TestSweets
  publisher_display_name: FilledStacks (Pty) Ltd
  identity_name: filledstacks.software.testsweets
  msix_version: 0.7.6.1
  certificate_path: ../certificate/CERTIFICATE.pfx
  certificate_password: ************
  publisher: E = dane@filledstacks.com, CN = Dane Mackier, OU = FilledStacks Software, O = FilledStacks (Pty) Ltd, L = Cape Town, S = Western Cape, C = ZA
  capabilities: "internetClient"
`

**Comment by YehudaKremer** [comment]
Hello @eb-so 

I publish new version [3.1.3](https://pub.dev/packages/msix) with fix,
please check if its solve the problem.

also, please make sure you running the latest version,
the bars ("❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚") in the logs are from older version (v2).

**Comment by eb-so** [comment]
@YehudaKremer Thank you for your quick response

It stops it from failing but now it hangs forever 

This is my workflow in github action 
```
name: Windows Build And Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  create_release:
    name: Build Windows Release
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
          flutter-version: "2.10.1"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

      - run: git config --system core.longpaths true
      - run: flutter pub get
        working-directory: src/application
      - run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: src/application
      - run: flutter test
        working-directory: src/application
        
      # Build for windows and Create the msix windows installer
      - run: flutter pub run msix:create
        working-directory: src/application

```

**Comment by eb-so** [comment]
I think it hangs cause I need to accept the install certificate dialog right?

**Comment by eb-so** [comment]
Here is the verbose log
<img width="1019" alt="Screen Shot 2022-02-18 at 2 38 25 PM" src="https://user-images.githubusercontent.com/89080323/154675922-7b4522a6-6dd7-47ca-97fc-db0c84ec1789.png">

**Comment by YehudaKremer** [comment]
True, you can overpass this by using the `install_certificate: false` configurating or `msix:create --install-certificate false` cli option

**Comment by eb-so** [comment]
@YehudaKremer Thank you it worked 🎆 🎆 🎆

**Comment by YehudaKremer** [comment]
Glad to hear that.
