### ISSUE TITLE
[BUG] runFullTrust

### ISSUE THREAD

**Issue by nguyenhuuta** [YehudaKremer/msix#110]
### :information_source: runFullTrust
I'm using msix version: ^3.2.0 and when I build the MSIX file for distribution to the Windows Store I get a **runFullTrust** error in **Package.appxmanifes**t. 
Please show me how to fix this error.

**Comment by YehudaKremer** [comment]
When you submit to the store there is a warning about `runFullTrust` capability,
just write them that your app is a .msix app for desktop, therefore, is required to have runFullTrust capability.

see more details:
[https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations):

![image](https://user-images.githubusercontent.com/946652/157040605-d5ab359b-06f1-4b1f-b701-a6f263fc7efc.png)

**Comment by nguyenhuuta** [comment]
Dear Yehuda Kremer,
Thank you for your email,
I will try

Best regards,

Vào Th 2, 7 thg 3, 2022 vào lúc 20:11 Yehuda Kremer <
***@***.***> đã viết:
