### ISSUE TITLE
[FEATURE REQUEST] Allow `msix_config` to be read elsewhere

### ISSUE THREAD

**Issue by lijy91** [YehudaKremer/msix#111]
### :speech_balloon: Description
I created a packaging and publishing tool that supports packaging into multiple formats, I want to make msix package by relying on msix, but now it can only be configured through pubspec, I want to allow passing in msix_config through Dart side.

https://github.com/leanflutter/flutter_distributor/issues/17

**Comment by YehudaKremer** [comment]
Hello @lijy91 

All the configurations in this package can be configured with command-line arguments (see the [configurations tables](https://github.com/YehudaKremer/msix#available-configurations)),
so you can leave the pubspec empty and work only with command-line arguments.

For example:
```dart
() async {
  await Msix([
    '--display-name',
    'Flutter App Release',
    '--build-windows',
    'false'
  ]).create();

  print('done');
  }
```

Please let me know if its works for you.

**Comment by lijy91** [comment]
I think I missed this, I will try to integrate him into flutter_distributor

**Comment by YehudaKremer** [comment]
Great, I'm here if you need any help doing that.
good luck
