### ISSUE TITLE
[BUG] Microsoft Review states: The available product tile icons include a default image.

### ISSUE THREAD

**Issue by lehnen** [YehudaKremer/msix#112]
Submitting the msix in the partner portal of microsoft leads to this message in the verification process:
`The available product tile icons include a default image`

Here's my config:

`msix_config:`
`  display_name: APP Name`
`  app_installer: #<-- app installer configuration`
`    publish_folder_path: OUPUTPATH`
`    hours_between_update_checks: 0`
`    automatic_background_task: true`
`    update_blocks_activation: true`
`    show_prompt: true`
`    force_update_from_any_version: false`
`  store: true`
 ` publisher_display_name: XYZ`
 ` publisher: CN=XYZ`
 ` identity_name: XYZ`
 ` msix_version: 1.0.0.0`
`  capabilities: internetClient`
`  logo_path: PATH TO A PNG FILE`
`  start_menu_icon_path: PATH TO A PNG FILE`
`  tile_icon_path: PATH TO A PNG FILE`

I did not find any info on a description page of this package that adddresses this error.

I am glead for any help on this.

Greetings
Volker

**Comment by YehudaKremer** [comment]
Hey

did you provide a valid icon in `logo_path:`? (not the default flutter logo)
what `msix` package, version are you using?

make sure you do not submit your app as an Xbox product...

Microsoft will approve your app submission to the public, only if it's valid and have a unique icon and all other details in the product submission are valid.
