### ISSUE TITLE
[FEATURE REQUEST] Ability to specify additional `protocol_activation`

### ISSUE THREAD

**Issue by imranismail** [YehudaKremer/msix#114]
### :speech_balloon: Description
Allow additional `protocol_activation` to be specified,

Use-case:

Allow app to be assigned as default handlers for `http` and `https` protocol.

Although unrelated, I have a few more questions with regards to my request. Let's say the default browser was overridden, how do I add a function to reassign the default browser.

I have this sample code:

```dart
void configure() {
  final hkcu = Registry.currentUser;
  final http = hkcu.createKey(
      r'Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice');
  final https = hkcu.createKey(
      r'Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice');
  // setting the executable path does not work
  // it wants the ProgId and I have no clue where to get this from
  final progId = RegistryValue(
      'ProgId', RegistryValueType.string, Platform.resolvedExecutable);

  http.createValue(progId);
  https.createValue(progId);
}
```

### :question: Platform
Windows

**Comment by YehudaKremer** [comment]
Hello @imranismail 

You can now (version 3.4.0) add multiple protocols, see: [changelog](https://pub.dev/packages/msix/changelog).

Thank you
