### ISSUE TITLE
[DOCUMENTATION] What does `add_execution_alias` do?

### ISSUE THREAD

**Issue by CaptainDario** [YehudaKremer/msix#116]
From reading the documentation

>Add an alias to active the app, use the pubspec.yaml name: value, so if your app calls 'Flutter_App', user can activate the app using flutterapp command.

I thought that I can run my app from cmd. However, this does not seem to be the case.
What does this option do?

**Comment by YehudaKremer** [comment]
Yes, should run from cmd.
 Set it to true.

What in your
```yaml
name:
```
?

בתאריך יום ב׳, 14 במרץ 2022, 22:46, מאת CaptainDario ‏<
***@***.***>:

**Comment by CaptainDario** [comment]
Okay, I set the value to the name I want my app to be run from.
Is there a way to set the alias?

**Comment by CaptainDario** [comment]
I set it to true:

``` yaml
msix_config:
  add_execution_alias: true
```

And this is set to:

``` yaml
name: da_kanji_mobile
```

Now I can run it via da_kanji_mobile, but I would like to run it via dakanji

**Comment by YehudaKremer** [comment]
Hello @CaptainDario 

You can now (version 3.4.0) set the execution alias, see: [changelog](https://pub.dev/packages/msix/changelog)

Thank you

**Comment by CaptainDario** [comment]
Thank you very much for this quick update!
