### ISSUE TITLE
How to make it work on desktop/Windows without Microsoft Store??

### ISSUE THREAD

**Issue by Ros4111** [YehudaKremer/msix#117]
I am trying your fantastic package, I could create a msix without problems. After create it I can install the app that works great on Windows.

I would like to upload the new versions to my hosting but I dont see how to setup the URL where the app should check for updates. Can someone tell me where is this setting?
I dont want to publish it on Windows Store.

My actual setting on pubspect.yaml is:
msix_config:
  display_name: 'My App CMS'
  publisher_display_name: My Company
  identity_name: 48434MySoftware.MyAPP
  msix_version: 1.4.5.0
  store: false
  app_installer:
    publish_folder_path: .\instalable
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  install_certificate: false

Thanks a lot. We apreciate your hard work

**Comment by richard457** [comment]
If you use the windows store then you don't need to check within your app for update windows store will do that for you, however if you need to use custom server, I think at this time it is not even possible with flutter but I might be wrong on that.

**Comment by markbreuss** [comment]
Although this might be out of scope of this package @YehudaKremer ?
We are a company looking into using flutter for a windows project and need a custom auto_update server.

**Comment by YehudaKremer** [comment]
Hello @markbreuss 

Can your distribution be via file share?
if so, you can use [App Installer](https://github.com/YehudaKremer/msix#-publishing-outside-the-store).

**Comment by markbreuss** [comment]
Thanks for the fast response!

No the app must be distributed to severs devices at different locations.

**Comment by YehudaKremer** [comment]
You can use file share in "different locations" as long as you use the same company network.
File share also using URL for example "files://server/appfolder/app.appinstaller".

you can use HTTP protocol as long as you have the company certificate installed on all the user's pcs,
also, it will need to [enable](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/disabling-the-msix-ms-appinstaller-protocol-handler/ba-p/3119479) the "ms-appinstaller" protocol to the company network pcs.
