### ISSUE TITLE
[BUG] SignTool fails to handle spaces in path

### ISSUE THREAD

**Issue by theAeon** [YehudaKremer/msix#119]
### :information_source: Info

**Version: `3.4.0`**

### :speech_balloon: Description

In the constructor for `getCertificateDetails.certificateDetailsProcess` the powershell command does not sanitize `$powershellSubjectOutputFilePath` properly and fails when there is a space in the path. Easily fixable by single-tick quoting the variable.

**Comment by YehudaKremer** [comment]
Hello @theAeon 

Thanks for the report

fix like that: https://github.com/YehudaKremer/msix/commit/cd8d0763e9b05c9d36b71295719247fab98fd113 
?

**Comment by YehudaKremer** [comment]
I publish a new version (3.4.1) with this fix, please check if it solves the problem.

**Comment by theAeon** [comment]
yup, all set.
