### ISSUE TITLE
[FEATURE REQUEST] Support relative paths in `logo_path` and `certificate_path`

### ISSUE THREAD

**Issue by mgenware** [YehudaKremer/msix#121]
### :speech_balloon: Description

I noticed these fields are written in absolute paths in [examples](https://pub.dev/packages/msix/example). Any chance to support relative paths? because those absolute paths enforce other team members to have the exact file structure like me.

**Comment by YehudaKremer** [comment]
Hello @mgenware 

Relative path also works, for example
```taml
logo_path: ./logo.jpg
```

**Comment by mgenware** [comment]
@YehudaKremer Awesome!
