### ISSUE TITLE
Question on how to add dll and VCRedist as dependency

### ISSUE THREAD

**Issue by j0chn1** [YehudaKremer/msix#122]
Hey there,
I am sorry to misuse your issue tracker for this question, but I am searching for 3 hours now and got no step further.
My app depends on libsodium and VCRedist. 
I'd like to add both to my msix and publish it, but I do not know how.
It is no problem to add provide the libsodium.dll but I don't have a clue how to add it to the msix and unpack it to C:\Windows\System32.
Same applies to VCRedis as installer. 
I do not need it to add those with help of you plugin (yet), but if you can provide me a guide whether written by you or foun don the internet, I would be very glad and thankful :)
Thank you very very much in advance.
Regards j0chn

**Comment by YehudaKremer** [comment]
Hello @j0chn1 

You can try this solved issue: https://github.com/YehudaKremer/msix/issues/115

**Comment by j0chn1** [comment]
Hello @YehudaKremer,
thank you for your fast answer.
If I get it correctly, I can add "assets_directory_path" to the msix config and it is packed within the msix whereas the last subfolder is the folder within the msix (e.g. C:\user\myuser\flutter_project\libs results in msix->\libs\)
Then in my main.dart or before I need the library I can load it via:
DynamicLibrary.open(pathToLib(e.g)\libs\xyz.dll));
Am I right?

**Comment by YehudaKremer** [comment]
see also https://github.com/YehudaKremer/msix/issues/145#issuecomment-1268834246
