### ISSUE TITLE
[BUG] Am keeping on getting unauthorized app message even when am using the test certificate.pfx 

### ISSUE THREAD

**Issue by mlg-hub** [YehudaKremer/msix#124]
### :information_source: Info

**Version: `e.g. v2.8.15`**

### :speech_balloon: Description

**Enter a description of your problem here.<br />
Any logs, error and assets you have that can help to find this bug.<br />
To run the tool with extended logs use the `-v` argument, for example: `flutter pub run msix:create -v`**

### :scroll: Pubspec.yaml

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

**Comment by YehudaKremer** [comment]
Hey, Sorry for the late response.
Please try the latest version.
