### ISSUE TITLE
[BUG] RangeError (start): Invalid value: Not in inclusive range 0..57: -1

### ISSUE THREAD

**Issue by JagandeepBrar** [YehudaKremer/msix#129]
### :information_source: Info

**Version: v3.6.1**

### :speech_balloon: Description

When trying to build an MSIX using a custom output path set, the build fails with the following error:

```bash
running "flutter build windows"...     65.1s
building msix files...                 4.5s
packing msix files...                  2.6s
Unhandled exception:
RangeError (start): Invalid value: Not in inclusive range 0..57: -1
#0      RangeError.checkValidRange (dart:core/errors.dart:351:7)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      Msix._msixOutputPath (package:msix/msix.dart:91:26)
#3      Msix._printMsixOutputLocation (package:msix/msix.dart:141:42)
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:///C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.6.1/bin/create.dart:4:3)
```

If `--output-path` is not set, the build completes successfully. v3.5.1 works as expected, v3.6.0 is the first version where this starts to occur.

Note that the actual MSIX does get packaged and outputted to the right location, but it throws trying to print the path to the MSIX file. Since it returns an error, it causes CI/CD scripts to fail which is causing it to be a breaking change for us.

**Comment by YehudaKremer** [comment]
Hello @JagandeepBrar 

I Publish new version (3.6.2) with a fix for that,
please check if it solves this problem for you.

Thank you for reporting this bug! 👍

**Comment by JagandeepBrar** [comment]
Sorry for the delay but I can confirm that it 3.6.2 fixes the issue, thank you!
