### ISSUE TITLE
Creating a msix is working but I cannot install it

### ISSUE THREAD

**Issue by chrisDK1977** [YehudaKremer/msix#131]
Creating a msix is working but I cannot install it because of:

_This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)_

I was going this way: https://docs.flutter.dev/desktop#msix-packaging
-> ... Use the following instructions to generate a self-signed .pfx certificate...

How can I get to work it on my local machine and how can I get it to work inside a company without the windows app store as it is just interesting for a few people? 
How can I get a  certificate signed by a Certificate Authority known to Windows (_Distributing your application by self hosting it on a website requires a certificate signed by a Certificate Authority known to Windows._)

**Comment by austinn** [comment]
I am also having this issue

**Comment by daydreary** [comment]
I found a way to install for test.
Right click your msix file, then properties-digital signature-details-view certification-install.
Install into the trusted root certification organization. Then the msix can install.

**Comment by YehudaKremer** [comment]
@daydreary Thanks for your solution.
