### ISSUE TITLE
Cannot install App Package - This .appinstaller file is using a new schema ...

### ISSUE THREAD

**Issue by chrisDK1977** [YehudaKremer/msix#134]
I get the error:
This .appinstaller file is using a new schema which is not valid on this OS version. Please update to the latest version of Windows 10.

but Windows update does show me that my system is "Up to date".

**Comment by YehudaKremer** [comment]
https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues

**Comment by khanliKU** [comment]
I got the same error when I ran "flutter pub run msix:publish"

My OS build is 19042.1586. The page says:

_"Windows 10 1909 and earlier:
The device must be enabled for Developer Mode or Sideloading apps. See [Enable your device for development](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development) to learn more."_

Developer Mode was already enabled for me.
![image](https://user-images.githubusercontent.com/25869028/170652968-2a519057-717f-4cb1-8869-1072ab7fd61c.png)

However I was able install my app using the msix I created by running "flutter pub run msix:create"

FYI

**Comment by carminechoi** [comment]
Changing the xmlns in the appinstaller from "http://schemas.microsoft.com/appx/appinstaller/2021" to "http://schemas.microsoft.com/appx/appinstaller/2018" fixed it for me

**Comment by jhiggs15** [comment]
Anyone know if there is a way to set xmlns from msix_config?

**Comment by YehudaKremer** [comment]
Hello

I publish a new version (3.6.3) with @carminechoi suggestion, thank you.
