### ISSUE TITLE
[BUG] When tapping a push notificiation from a service like local_notifier it opens a new window

### ISSUE THREAD

**Issue by ollyde** [YehudaKremer/msix#136]
```
  local_notifier: ^0.1.4
  msix: ^3.6.2
```

This only happens with mxis, using ```flutter build windows --release``` it's fine.

Something is up with the msix package opening new versions

**Comment by ollydixon** [comment]
This also breaks the window_manager plugin as well. https://pub.dev/packages/window_manager#isalwaysontop

**Comment by YehudaKremer** [comment]
Hello

On the latest Msix version with the notification package: [Win Toast](https://pub.dev/packages/win_toast), its works fine for me.
please reopen this issue if its still happens for you.

**Comment by AnAlpaca** [comment]
I am now having the same issue
