### ISSUE TITLE
[QUESTION] How to sign the msix using SECTIGO / COMODO?

### ISSUE THREAD

**Issue by petodavid** [YehudaKremer/msix#138]
I just received my usb eToken and installed SafeNet client. How can I sign the msix?

**Comment by YehudaKremer** [comment]
Hello

You can use the set configuration field `sign_msix` to `false`,
and after the msix is created you can sign it yourself like a standard msix file. 
https://learn.microsoft.com/en-us/windows/msix/package/signing-package-overview
