### ISSUE TITLE
[FEATURE REQUEST] Can we make msix not depend on flutter?

### ISSUE THREAD

**Issue by lijy91** [YehudaKremer/msix#139]
### :speech_balloon: Description

This tool doesn't seem to need to run in a flutter app, can we remove the flutter-related dependencies to make it a pure dart tool? I'm using msix in flutter_distributor and when I use melos bootstrap it doesn't do dependency installation correctly.

```
Resolving dependencies...
Because app_package_maker_msix requires the Flutter SDK, version solving failed.
Flutter users should run `flutter pub get` instead of `dart pub get`.
BootstrapException: Failed to install.: app_package_maker_msix at /Users/lijy91/Documents/Projects/leanflutter/flutter_distributor/packages/app_package_maker_msix.
```

**Comment by YehudaKremer** [comment]
done in https://github.com/YehudaKremer/msix/commit/a7eb22842483891d9e28212890d58b4dbca05e85
