### ISSUE TITLE
[FEATURE REQUEST] How to use misx with different entry points

### ISSUE THREAD

**Issue by anik786** [YehudaKremer/msix#143]
### :speech_balloon: Description
Normally if you wanted to build with flutter with a different entrypoint we would use:
```
flutter build windows -t lib\entrypoint\staging.dart
```

However it is not possible to do this with "msix:create"
```
flutter pub run msix:create -t lib\entrypoint\staging.dart # error
```

Can we update the command so that all unused arguments are passed on to the flutter build. Or alternatively, have a `--build-args` flag that can be passed onto flutter. e.g,

```
flutter pub run msix:create --build-args "-t lib\entrypoint\staging.dart"
```

### :question: Platform
All platforms

**Comment by YehudaKremer** [comment]
You can run 
```console
flutter build windows -t lib\entrypoint\staging.dart
```
then run 
```console
flutter pub run msix:create --build-windows false
```
