### ISSUE TITLE
[FEATURE REQUEST]: 3rd party DLLs Windows 10

### ISSUE THREAD

**Issue by magicmatt007** [YehudaKremer/msix#145]
### :speech_balloon: Description
msix 2.5.5 mentiones how to use DLLs in the section **".dll Files And Assets (FFI Library"** 

  by using

assets_directory_path:  'C:\Users\me\flutter_project_name\myAssets'

It seems, that this is not supported in the current msix 3.6.2 version anymore. It's not in the documentation, nor does it seem to work....

How can I use 3rd party DLLs with the current misx 3.6.2 version?

### :question: Platform
Windows 10

Many thanks!

**Comment by YehudaKremer** [comment]
hello

Can you try manually putting your dlls in the build directory (build\windows\runner\Release),
I don't think it will delete by the **build** or **create** scripts

**Comment by magicmatt007** [comment]
Thanks Yehuda.

I was able to get it running by adding the DLLs to a "normal" assets folder and then adjusting the path for opening it manually whenever I assemble an MSIX. Somehow inspired by this suggestions, but without the intelligence :-) https://www.anycodings.com/questions/how-to-include-dlls-in-flutter-build-windows

That said, it would be great if there was are more integrated and automated solution, as it seemed to be available in previous versions of the MSIX plugin.

Any idea, why this has disappeared?

**Comment by YehudaKremer** [comment]
Hey

You can put your files in the build folders (release/debug) and flutter or msix will not delete them in future builds.
