### ISSUE TITLE
[FEATURE REQUEST] Need args for bypass y\N in CI

### ISSUE THREAD

**Issue by fatsolko** [YehudaKremer/msix#147]
### :speech_balloon: Description
When i run in gitlab CI msix:create and try signing msix, need confirm y/N, but args --yes or /Q /S, dont work.

```

Step 40/42 : RUN flutter pub run msix:create --build-windows false --install-certificate true --certificate-path cert.pfx --certificate-password 1312
 ---> Running in 5941220a36d8
building msix files...                  /-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\9.2s
packing msix files...                   /-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/ 
? Do you want to install the certificate: "cert.pfx" ? (y/N) 
The command 'cmd /S /C flutter pub run msix:create --build-windows false --install-certificate true --certificate-path cert.pfx --certificate-password 1234' returned a non-zero code: 3221225786
```

**Comment by YehudaKremer** [comment]
Hello

From the documentation:
![image](https://user-images.githubusercontent.com/946652/183768640-e68599eb-eb8d-47c2-bb25-8c3815b5f397.png)

**Comment by fatsolko** [comment]
![изображение](https://user-images.githubusercontent.com/76652885/183840311-704797d1-8f94-4da8-b566-c11bf12be47f.png)
I put this up and it doesn't help

**Comment by YehudaKremer** [comment]
Hello 

The install certificate step is interactive, so for CI process you want to skip it by turning it off: `--install-certificate false`

**Comment by fatsolko** [comment]
in this case, the app will be signed with a test certificate. 
I need my certificate.  And so that I can skip yes/no in the CI pipeline.
![изображение](https://user-images.githubusercontent.com/76652885/183842603-799123af-9e77-4c8c-b8fd-0f188d4b39f5.png)

**Comment by YehudaKremer** [comment]
Did you use the `--certificate-path cert.pfx --certificate-password 1312` args and still got signed with the test certificate?

**Comment by fatsolko** [comment]
No, I'm getting a request  `Do you want to install the certificate: "contoso.pfx" ? (y/N)` which I can't confirm in CI

**Comment by YehudaKremer** [comment]
If we looking at your other issue (https://github.com/YehudaKremer/msix/issues/146) we have the command:
`flutter build windows -t lib/environment/main_dev.dart "&" flutter pub run msix:create --build-windows false --certificate-path cert.pfx --certificate-password 1312 --install-certificate false`

Can you please try it

**Comment by fatsolko** [comment]
It works! I recommend changing the description, as it is not clear from the documents how this works.
