### ISSUE TITLE
[BUG] Version with a large number

### ISSUE THREAD

**Issue by fatsolko** [YehudaKremer/msix#149]
When a version uses a long number, a build error occurs.

![изображение](https://user-images.githubusercontent.com/76652885/184097884-676fe13f-ad00-43f5-b96e-29f9dc88ebd5.png)
When a version uses a short number, build has no error.

![изображение](https://user-images.githubusercontent.com/76652885/184097871-e4d7bf22-a6f6-43c3-8962-1fb4cc280e42.png)

**Comment by fatsolko** [comment]
65535 work. 65536 don't work

**Comment by YehudaKremer** [comment]
Hello

This is msix-tool behavior: https://github.com/microsoft/WindowsAppSDK/issues/148
![image](https://user-images.githubusercontent.com/946652/188872158-fcebc87f-0eae-4049-b2c6-4655fe8b883f.png)
