### ISSUE TITLE
[FEATURE REQUEST] Allow setting certificate credentials via ENV vars

### ISSUE THREAD

**Issue by MTRNord** [YehudaKremer/msix#15]
### :speech_balloon: Description
We use this in a CI and the current config only allows to set the password in the pubspec.yaml file.
This leads to leaking our password. Instead we would like to be able to provide the password via an env var.

An added bonus would be to also provide the cert base64 encoded via a variable as that would eliminate the step to write it from the env to a file.

**Comment by YehudaKremer** [comment]
hello @MTRNord 
i added the password via the command-line arguments like you ask, in version 0.1.6
the "bonus" feature not done, maybe will do in future version.

thanks for the feature request.

**Comment by MTRNord** [comment]
Thanks :)

**Comment by YehudaKremer** [comment]
@MTRNord  see: [https://pub.dev/packages/msix#command-line-arguments](https://pub.dev/packages/msix#command-line-arguments)

**Comment by MTRNord** [comment]
Already went ahead and implemented it in our CI :) I was keeping an eye on the repository :3
