### ISSUE TITLE
[BUG] Signed MSIX generation using CLI argments fails on publisher extraction if cert password contains an ampersand

### ISSUE THREAD

**Issue by qdot** [YehudaKremer/msix#153]
### :information_source: Info

v3.6.3

### :speech_balloon: Description

When using the `--certificate_password` CLI argument for passing in a cert password (for CI purposes), if the cert password includes an ampersand, the msix:create command will fail when extracting the publisher information.

```
Get-PfxData : The password is incorrect. However, the PFX file you are importing is group-protected or has a
null/empty password. Re-run the command without -Password parameter to unpack the PFX.
At line:1 char:2
+ (Get-PfxData -FilePath ".\cert.pfx" -Password $(ConvertTo-SecureStrin ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-PfxData], ArgumentException
    + FullyQualifiedErrorId : GetPfxDataFailure,Microsoft.CertificateServices.Commands.GetPfxDataCommand
```

Neither switch-quoting (using `'` and `"` in succession) nor triple-quoting `"""` the string on the command line seem to fix this.
 
Including the same password using the `certificate_password` property in the yaml file works fine and the installer signs properly.

**Comment by YehudaKremer** [comment]
Hello @qdot 

Can you try https://github.com/YehudaKremer/msix/issues/132#issuecomment-1131472692
