### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by devius** [YehudaKremer/msix#158]
### :information_source: Info

**Version: `[e.g. 3.7.0]`**

### :speech_balloon: Description

Microsoft store provides this capability as restricted:
The following restricted capabilities require approval before you can use them in your app: runFullTrust

### :scroll: Pubspec.yaml

msix_config:
  display_name: ნავიგატორი
  publisher: CN=D35174D8-7272-4C29-9FCE-1CC0723B9364
  publisher_display_name: Davit Matchakhelidze
  identity_name: 38256DavitMatchakhelidze.35024535F3EA8
  msix_version: 1.0.0.0
  logo_path: .\assets\app_logo.png
  capabilities: internetClient
  store: true

**Comment by YehudaKremer** [comment]
see https://github.com/YehudaKremer/msix/issues/110#issuecomment-1060670731
