### ISSUE TITLE
[BUG] Unable to create MSIX file: Exception calling ".ctor" with "2" argument(s): "The specified network password is not correct.

### ISSUE THREAD

**Issue by danfleck** [YehudaKremer/msix#161]
### :information_source: Info
Version v3.7.0

### :speech_balloon: Description

Exception when executing the create command. 

`[ +271 ms] Unable to locate an Android SDK.
[  +21 ms] executing: [C:\Users\dan\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +7 ms] 0bb71df75f10a9ad740836568c730ed8aaede2d8
[   +2 ms] executing: [C:\Users\dan\flutter/] git tag --points-at 0bb71df75f10a9ad740836568c730ed8aaede2d8
[  +87 ms] Exit code 0 from: git tag --points-at 0bb71df75f10a9ad740836568c730ed8aaede2d8
[   +3 ms] executing: [C:\Users\dan\flutter/] git describe --match *.*.* --long --tags
0bb71df75f10a9ad740836568c730ed8aaede2d8
[  +87 ms] Exit code 0 from: git describe --match *.*.* --long --tags 0bb71df75f10a9ad740836568c730ed8aaede2d8
[   +2 ms] 3.6.0-13.0.pre-12-g0bb71df75f
[  +28 ms] executing: [C:\Users\dan\flutter/] git rev-parse --abbrev-ref --symbolic @{upstream}
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{upstream}
[   +2 ms] origin/master
[   +5 ms] executing: [C:\Users\dan\flutter/] git ls-remote --get-url origin
[  +61 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +83 ms] executing: [C:\Users\dan\flutter/] git rev-parse --abbrev-ref HEAD
[ +192 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] master
[  +83 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +123 ms] executing: C:\Users\dan\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --color run msix:create -v
[     0.019s] parsing cli arguments
[     0.240s] validating config values
[     0.282s] running "flutter build windows"...
[    20.080s] building msix files...
[    20.080s] validating build files
[    20.126s] cleaning temporary files
[    20.159s] create app icons
[    20.160s] generating icons
[    23.567s] copying VC libraries
[    23.581s] getting certificate publisher
[    23.581s] getting certificate "Subject" by file certificate
[    25.854s]
Unhandled exception:
new-object : Exception calling ".ctor" with "2" argument(s): "The specified network password is not correct.
"
At line:1 char:1
+ new-object System.Security.Cryptography.X509Certificates.X509Certific ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:59:7)
#1      SignTool._executePowershellCommand (package:msix/src/sign_tool.dart:84:11)
<asynchronous suspension>
#2      SignTool._getCertificateSubjectByFile (package:msix/src/sign_tool.dart:136:47)
<asynchronous suspension>
#3      SignTool.getCertificatePublisher (package:msix/src/sign_tool.dart:36:17)
<asynchronous suspension>
#4      Msix._buildMsixFiles (package:msix/msix.dart:114:7)
<asynchronous suspension>
#5      Msix._createMsix (package:msix/msix.dart:98:5)
<asynchronous suspension>
#6      Msix.create (package:msix/msix.dart:57:5)
<asynchronous suspension>
#7      main (file:///C:/Users/dan/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.7.0/bin/create.dart:4:3)
<asynchronous suspension>
[+28198 ms] "flutter run" took 25,582ms.
[  +26 ms] pub finished with exit code 255
[  +12 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:250:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[ +109 ms] ensureAnalyticsSent: 87ms
[  +12 ms] Running 0 shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +4 ms] exiting with code 255

**Pubspec File:**
[pubspec_REDACTED.yaml.txt](https://github.com/YehudaKremer/msix/files/10136378/pubspec_REDACTED.yaml.txt)

**Comment by sbeckmann** [comment]
I had the same issue. In my case it was due to a special character ($) in the .pfx certificate's password. 

A workaround is to set the `--sign-msix` flag to `false` and sign the msix package yourself using SignTool.exe or of course changing the certificate's password.
