### ISSUE TITLE
Auto Update Outside the Store

### ISSUE THREAD

**Issue by anggoran** [YehudaKremer/msix#167]
I found on the docs that there is a parameter named `hours_between_update_checks`, but I cannot find something like `feedURL` as a link that provide `auto update` functionality. Is it still possible to do `auto update` without publishing to store (using web page or appcast)?

**Comment by YehudaKremer** [comment]
Hello

Auto update outside the Microsoft store are available via the [App Installer](https://github.com/YehudaKremer/msix#-publishing-outside-the-store) feature.

This future can use only by organization that have certificate installed on the organization users machines,
and used that certificate to sign the Msix file.

So if is your situation, you can use [App Installer](https://github.com/YehudaKremer/msix#-publishing-outside-the-store).

About auto update source, for now, its available only from file-share and not from the web:
![image](https://user-images.githubusercontent.com/946652/210219651-a13a743c-2e18-4d83-bb68-555a267dba65.png)
