### ISSUE TITLE
[BUG] The attribute 'Version' with value '3.1.2301.0006' failed to parse.

### ISSUE THREAD

**Issue by AjinkyaKale** [YehudaKremer/msix#169]
### :information_source: Info
**Version: `e.g. v3.7.0`**

### :speech_balloon: Description

We have specified our msix version as "**msix_version: 3.1.2301.0006**" under "**msix_config**".<br />
However, after running **flutter pub run msix:create** command, we get flutter build error as below.<br />
'3.1.2301.0006' violates pattern constraint of '(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){3}'.

The attribute 'Version' with value '3.1.2301.0006' failed to parse.<br />

Tried to run the command with extended logs : `flutter pub run msix:create -v` generates below output,

**PS D:\StudioProjects\Client> flutter pub run msix:create -v** 
////////////////////////// _Excluded some unused logs_ ////////////////////////////////////
Using "\\?\D:\StudioProjects\Client\build\windows\runner\Release\AppxManifest.xml" as the manifest for the package.
MakeAppx : error: Failure at appxFactory->CreateManifestReader(manifestStream, &manifestReader) - 0x80080204 - The specified package format is not valid: The package manife
st is not valid.
MakeAppx : error: Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Identity" and
 namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/@**Version
'3.1.2301.0006' violates pattern constraint of '(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])(\.(0|[1-9][0-9]{0,3}|[1-5][0-9]{4}|
6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])){3}'.
The attribute 'Version' with value '3.1.2301.0006' failed to parse.**
Cleaning up output file "\\?\D:\StudioProjects\Client\build\windows\runner\Release\pos_flutter.msix".
MakeAppx : error: Failure at (CreatePackage( overwrite, hashAlgorithm, fileList, outputPath, manifestStream.Get(), forceCompressionNone, performanceOptions, encryptPackage,
 encryptionOptions, cgmPath, mainPackagePathForResourceExemption, makepriExeFullPath)) - 0x80080204 - The specified package format is not valid: The package manifest is not
 valid.
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.

Unhandled exception:

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:59:7)
#1      MakeAppx.pack (package:msix/src/makeappx.dart:28:9)
<asynchronous suspension>
#2      Msix._packMsixFiles (package:msix/msix.dart:125:5)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:99:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:57:5)
<asynchronous suspension>
#5      main (file:///D:/Android/flutter_windows_3.3.10-stable/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.7.0/bin/create.dart:4:3)
<asynchronous suspension>
[+34290 ms] "flutter run" took 34,489ms.
[   +5 ms] pub finished with exit code 255
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:418:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:249:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

[ +199 ms] ensureAnalyticsSent: 193ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 255

### :scroll: Pubspec.yaml

Pubspec.yaml file looks like below,

msix_config:
  msix_version: 3.1.2301.0006
  display_name: XXXXX
  publisher_display_name: XXXXX
  identity_name: xxxxxxxxxxxxxx
  certificate_path: .\assets\CERTIFICATE.pfx
  certificate_password: Welcome@123
  logo_path: .\assets\images\sample.png
  publisher: E = xxxx, CN = xxxx OU = xxxxxx, O = xxxx, L = xxxx, S = xxxxx, C = xxxxxx
  icons_background_color: 'transparent'
  architecture: x64
  capabilities: 'internetClient,location,microphone,webcam'

flutter_intl:
  enabled: true

**Comment by YehudaKremer** [comment]
Hello

You can't have build number start with 1.2.3.**0001**, its need to start with positive number: 1.2.3.**1001**
