### ISSUE TITLE
[FEATURE REQUEST] Use Environment Variables for dynamic configuration

### ISSUE THREAD

**Issue by Iri-Hor** [YehudaKremer/msix#176]
### :speech_balloon: Description
Assume one wants to build different application versions for dev, stage and prod. Then it would be nice, if it was possible to use environment varaibles for a dynamic configuration in the pubspec.yaml. Otherwise one had to change the msix-config section in the pubspec.yaml each time.

### :question: Platform
Windows

**Comment by YehudaKremer** [comment]
Hello

I think this is duplicated with https://github.com/YehudaKremer/msix/issues/177
