### ISSUE TITLE
[FEATURE REQUEST] Support for Flutter Flavors

### ISSUE THREAD

**Issue by tfbsza** [YehudaKremer/msix#177]
### :speech_balloon: Description
In our project we use several flavors to distinguish between local development, staging, user acceptance testing and production environments. Each one is built using the --flavor command line argument which essentially tells the build to use a specific app point of entry, e.g. main_test.dart instead of the default main.dart, e.g.

`--flavor test -t lib/main_test.dart`
`--flavor uat -t lib/main_uat.dart`

It's necessary since different environments have different configuration for end-points they connect to, what keys they use for things like Google Analytics and so forth.

Could support for the above please be considered for Msix?

### :question: Platform
This is a feature request for Msix for Windows.

**Comment by YehudaKremer** [comment]
Hello

I can't see how it's relevant to the Msix package,
you rarely use the Msix package, only for testing or when publishing to the store.

For other useges maybe the [flutter_dotenv](https://pub.dev/packages/flutter_dotenv) package can help you.

**Comment by tfbsza** [comment]
In our case, we are not currently using the store and wanted to provide a downloadable .msix installer for our application instead. It's not so much the flavor part that's an issue, it's that we can't specify an additional build configuration element that relates to the -t command line argument for normal flutter builds, e.g:

    msix_config:
      display_name: AppName
      publisher_display_name: PublisherName
      identity_name: publisher.name.here
      msix_version: 1.0.3.0
      logo_path: c:\path\to\logo.png
      capabilities: internetClient

      #desired functionality
      main_entry: main_test.dart

**Comment by shubhamsinghshubham777** [comment]
This is an important feature, @YehudaKremer please consider opening this again and giving us an option to select the flavor/target-file
