### ISSUE TITLE
[BUG]No "windows-build-args" option

### ISSUE THREAD

**Issue by KentaIbayashi** [YehudaKremer/msix#184]
msix version 3.7.0
I want to add an argument when msix:create build windows app.

command
`flutter pub run msix:create --windows-build-args=--dart-define=FLAVOR=dev`
and then output is here
`Unhandled exception:
FormatException: Cound not find an option named "windows-build-args"`

I also tried to add "windows_build_args: --dart-define=FLAVOR=dev" to pubspec.yaml, but the output is the same.

Any solution?

**Comment by YehudaKremer** [comment]
Hey
Yuo need newer version for that
https://github.com/YehudaKremer/msix/blob/main/CHANGELOG.md#380

**Comment by KentaIbayashi** [comment]
Thank you:) I upgraded msix to 3.8.2 then worked with no error.
