### ISSUE TITLE
Support whole icon asset folder as generated by Visual Studio

### ISSUE THREAD

**Issue by technolion** [YehudaKremer/msix#19]
### :speech_balloon: Description
Currently msix only supports providing 3 images which get copied into the msix package:
- logo_path
- start_menu_icon_path
- tile_icon_path

In order to best show icons in Windows 10 multiple versions of these icons need to be copied into the msix package.
Especially there need to be plated and unplated versions and sizes for different screens.

When [creating all image assets with Visual Studio's Manifest Designer](https://docs.microsoft.com/en-us/windows/uwp/design/style/app-icons-and-logos#generating-all-assets-at-once) many different versions of the icons are created:
![assets](https://user-images.githubusercontent.com/1611505/107334721-5c001200-6ab7-11eb-86c4-1cc392670f2c.png)

The corresponding references in `Package.appxmanifest` look like this:

```
   <Logo>Assets\StoreLogo.png</Logo>
```

```
      <uap:VisualElements
        DisplayName="App1"
        Square150x150Logo="Assets\Square150x150Logo.png"
        Square44x44Logo="Assets\Square44x44Logo.png"
        Description="App1"
        BackgroundColor="transparent">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png" ShortName="App1" Square71x71Logo="Assets\SmallTile.png" Square310x310Logo="Assets\LargeTile.png"/>
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
```

As you can see the icons in the Assets folder do not have the exact file names as provided in the manifest file. They are still found in they correct size and for the correct occasion. This also fixes the problem that icons are shown _plated_ in the taskbar where you want to see them as _unplated_ (without empty space around them) version.

So, it would be great, if this package would get an option to provide a complete Asset folder as created by Visual Studio which get's then copied into the msix package. The `VisualElements` section of `Package.appxmanifest` would then have to look similar like the above.

**Comment by YehudaKremer** [comment]
Hello Thomas,
i added this feature to version `0.2.1-nullsafety.0`,
you can see documentation for this in the configuration table:

![image](https://user-images.githubusercontent.com/946652/107438682-8eeaea00-6b39-11eb-928a-68ea79341f5e.png)

please update me if this working for you

Thank you for this feature suggestion

**Comment by technolion** [comment]
Yehuda, that's awesome. Thanks a lot! I'll try it out.

**Comment by technolion** [comment]
Unfortunately `0.2.1-nullsafety.0` has dependency conflicts with the package `encrypt` which our application also needs, so I cannot test at the moment. I asked the maintainer of `encrypt` to provide a null-safety version as well.
So I will have to test this a little bit later.

Until then I have a quick question: 
Does the configuration option `vs_generated_images_folder_path` support building a file called resources.pri? This is necessary to support unplated (not on a colored plate with padding, but unpadded on transparent background) versions of the Windows 10 taskbar icons.

I had to spend half a day to find out, how that works. Here's my script that build our flutter application and packages it into an msix. The folder windows\Assets contains all images created by Visual Studio [like shown above](https://github.com/YehudaKremer/msix/issues/19#issue-804321068).

```
flutter clean
flutter pub get
flutter build windows
cp windows\AppxManifest.xml build\windows\runner\Release\
cp windows\*.dll build\windows\runner\Release\
cp -r windows\Assets build\windows\runner\Release\
cd build\windows\runner\Release\
makepri createconfig /cf priconfig.xml /dq en-US
makepri new /pr . /cf priconfig.xml
cd -
makeappx.exe pack /d build\windows\runner\Release /p build\TeamBeam.msix
```

**Comment by YehudaKremer** [comment]
yes `vs_generated_images_folder_path` using **makepri** cli to create proper resources.pri

**Comment by technolion** [comment]
perfect, thx. I will close this issue, as soon as I can test it.

**Comment by YehudaKremer** [comment]
@technolion i now added this change to the main version `0.1.12` that dont need nullsafety,
you can use it `msix: 0.1.12`.

**Comment by technolion** [comment]
I tested it and it works perfectly. Good work Yehuda, and thank you!
