### ISSUE TITLE
Can not run generated app on local machine

### ISSUE THREAD

**Issue by richard457** [YehudaKremer/msix#191]
**Version: `3.11.0`**

### :speech_balloon: Description
setting` store: false` and run  ` flutter pub run msix:create` the generated file can not be installed on a local machine
Eventhough I have accepted to install local certificate on windows

**Comment by dbrdz** [comment]
I had the same problem, but I found a [comment ](https://github.com/YehudaKremer/msix/issues/88#issuecomment-1031381351) in a different issue that pointed me to this link:

https://www.advancedinstaller.com/install-test-certificate-from-msix.html

after following these steps I was able to install the generated installer.

**Comment by richard457** [comment]
Thank you very much, it worked, be blessed.
