### ISSUE TITLE
[BUG] after updating flutter sdk to 3.10.0, msix packaging process stucked.

### ISSUE THREAD

**Issue by p1318k** [YehudaKremer/msix#193]
### :information_source: Info

**Version: `v3.11.1`**

### :speech_balloon: Description

it works fine with 3.7.12 flutter sdk.

**Comment by YehudaKremer** [comment]
> for example my log is https://github.com/sensuikan1973/pedax/actions/runs/4946108800/jobs/8843751064

we don't have readable logs here:
![image](https://github.com/YehudaKremer/msix/assets/946652/760d560a-c6c3-4523-809a-f3b0b853c179)

can some one provide me logs on this error (maybe run locally with the with -v flag)

on my pc i don't getting any error:
![image](https://github.com/YehudaKremer/msix/assets/946652/26ec9bf0-3a5e-4b4a-96ac-436e6b8bc8bf)

**Comment by YehudaKremer** [comment]
Can you please check if `dart run msix:create` works for you

**Comment by sensuikan1973** [comment]
ok, I'll do.

**Comment by YehudaKremer** [comment]
checking...

**Comment by p1318k** [comment]
@YehudaKremer Thanks for the quick update. I will check and leave the result.

**Comment by sensuikan1973** [comment]
Thank you so much for always being so courteous!

**Comment by p1318k** [comment]
@YehudaKremer I have another trouble with your fix. I file a new issue https://github.com/YehudaKremer/msix/issues/194. Please check and let me know if your need more debuging informations.
