### ISSUE TITLE
[BUG] after updating v3.12.0 from v3.9.1, signing failed.

### ISSUE THREAD

**Issue by p1318k** [YehudaKremer/msix#194]
### :information_source: Info

**Version: `v3.12.0`**

### :speech_balloon: Description
Regradless of flutter sdk version (3.10.0 or 3.7.12), it fails. 
It worked only with v3.9.1 package in my case.

Here are some logs.

[  +49 ms] executing: C:\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub run msix:create -v --signtool-options /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 /n 'SK Telecom Co.,Ltd.'
[     0.013s] parsing cli arguments
[     0.116s] validating config values
[     0.119s] running "flutter build windows"...
[    54.297s] building msix files...
[    54.298s] validating build files
[    54.306s] cleaning temporary files
[    54.314s] create app icons
[    54.315s] generating icons
[ 1m 02.534s] copying VC libraries
[ 1m 02.544s] getting certificate publisher
Unhandled exception:
invalid certificate subject: SK Telecom Co.,Ltd.
#0      SignTool._checkCertificateSubject (package:msix/src/sign_tool.dart:78:7)
#1      SignTool.getCertificatePublisher (package:msix/src/sign_tool.dart:48:7)
#2      Msix._buildMsixFiles (package:msix/msix.dart:114:24)
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:98:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:57:5)
<asynchronous suspension>
#5      main (file:///C:/Users/kimki/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.12.0/bin/create.dart:4:3)
<asynchronous suspension>
[+65903 ms] "flutter run" took 66,044ms.
[   +3 ms] pub finished with exit code 255
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:586:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:250:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>

**Comment by YehudaKremer** [comment]
Hello

Maybe its related to the recently PR: https://github.com/YehudaKremer/msix/pull/190

Do you have config value in the `publisher:` field under `msix_config:` ?
if so, try to delete `publisher` field, and run again (let the package automatically detect the certificate "Subject")

**Comment by p1318k** [comment]
Okay, I wll try. Thanks for the reply.

**Comment by p1318k** [comment]
@YehudaKremer it is working. Thank you.
