### ISSUE TITLE
[BUG] Do you want to install the certificate when dont_install_cert: true

### ISSUE THREAD

**Issue by gslender** [YehudaKremer/msix#195]
### :information_source: Info

Using msix v3.12.2

### :speech_balloon: Description
With the option in pubspec.yaml to be dont_install_cert: true I'm still prompted asking if I want to install the certificate??

Building package executable...
Built msix:create.
[     0.017s] parsing cli arguments
[     0.139s] validating config values
[     0.148s] running "flutter build windows"...
[    13.639s] building msix files...
[    13.640s] validating build files
[    13.648s] cleaning temporary files
[    13.660s] create app icons
[    13.661s] generating icons
[    20.909s] copying VC libraries
[    20.923s] getting certificate publisher
[    20.925s] getting certificate "Subject" by file certificate
[    21.242s] generate appx manifest
[    21.248s] generate package resource indexing files
[    21.360s] packing msix files...
[    21.361s] packing
[    23.687s] cleaning temporary files
[    23.979s] installing certificate
[    23.980s]
Do you want to install the certificate: "code.sign.certificate.pfx" ? (y/N) n <<<<<=== shouldn't this be silent ??
[ 1m 39.697s] signing
msix created: build/windows/runner/Release/myapp.msix

### :scroll: Pubspec.yaml

msix_config:
  logo_path: assets\icons\1024_trans.png
  trim_logo: false
  display_name: myapp
  publisher_display_name: G Slender
  identity_name: gslender
  msix_version: 1.6.0.16219
  certificate_path: certificate.pfx
  certificate_password: ######
  dont_install_cert: true

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

**Comment by YehudaKremer** [comment]
Hello

Look here 
https://github.com/YehudaKremer/msix/blob/main/CHANGELOG.md#breaking-changes-3

**Comment by grafst** [comment]
I have still the same issue with v3.16.1

my pubspec:
msix_config:
    display_name: xxx
    publisher_display_name: xxx
    identity_name: com.xx.xx
    msix_version: 0.0.0.1
    logo_path: 'assets\xxx.png'
    dont_install_cert: true
    show_prompt: false

<img width="1023" alt="2023-08-21_12-41-51" src="https://github.com/YehudaKremer/msix/assets/8471055/3bc793a4-5d65-4510-9bbc-aa69bbb1db43">

**Comment by grafst** [comment]
should I open a new issue?
