### ISSUE TITLE
[BUG] msix creates installer.exe instead of msix file ? What changed?

### ISSUE THREAD

**Issue by gslender** [YehudaKremer/msix#202]
Before I was running  msix: 3.13.1 but after upgrading to 3.14.0 the tool creates an installer.exe file instead of an msix file??

What did I miss in the change logs about this? Why is it doing this?

**Comment by gslender** [comment]
Super odd, but after running the tool again, it created the .msix file??? Not sure what's going on. Could this be related to the fvm change recently made??

**Comment by Tienisto** [comment]
Maybe flutter clean helps?

Also, this package should not be capable of compiling installer.exe, what you probably mean is a regular exe that gets created by `flutter build windows`

**Comment by YehudaKremer** [comment]
Sound like regression bug and related to: #203
