### ISSUE TITLE
[BUG] Signature should use timestamp flag

### ISSUE THREAD

**Issue by MTRNord** [YehudaKremer/msix#22]
### :information_source: Info

Version: `v0.1.12`

### :speech_balloon: Description

Currently the sign function used doesnt add a timestamp. This especially is problematic when the certificate used for a specific sign process gets used after the cert was invalid. As it currently cant know when it was signed the binary/msix would show up as not validly signed anymore. However with a timestamp it can verify it is still valid.

### Solution

The Code in question is https://github.com/YehudaKremer/msix/blob/main/lib/msix.dart#L169-L178

Adding `/tr http://timestamp.digicert.com` to that command is enough to solve this bug. If you want I will open a PR :)

**Comment by YehudaKremer** [comment]
Helllo Marcel :)

i added your code to the sign action: [https://github.com/YehudaKremer/msix/blob/main/lib/msix.dart#L178-L179](https://github.com/YehudaKremer/msix/blob/main/lib/msix.dart#L178-L179)
now vailable in version: msix: ^0.1.13

Thank you
