### ISSUE TITLE
[BUG]  Build fails with "RangeError (index): Index out of range" during icon generation

### ISSUE THREAD

**Issue by LucaBoss74** [YehudaKremer/msix#235]
### :information_source: Info

**Version: `v3.16.2`**

### :speech_balloon: Description

FINE: Package Config up to date.
[     0.022s] parsing cli arguments
[     0.114s] validating config values
[     0.117s] pack files in build folder: C:\Users\luca\Development\t3_fe\build\windows\runner\Release
[     0.124s] building msix files...
[     0.126s] validating build files
[     0.135s] cleaning temporary files
[     0.148s] create app icons
[     0.150s] generating icons
Unhandled exception:
RangeError (index): Index out of range: index should be less than 4576: 4600
#0      Uint8List.[]= (dart:typed_data-patch/typed_data_patch.dart:2280:7)
#1      ImageDataUint8.setPixelRgba (package:image/src/image/image_data_uint8.dart:111:9)
#2      Image.setPixel (package:image/src/image/image.dart:761:11)
#3      copyResize (package:image/src/transform/copy_resize.dart:132:15)
#4      Assets.createIcons.generateIcon (package:msix/src/assets.dart:67:26)
#5      Assets.createIcons.<anonymous closure> (package:msix/src/assets.dart:140:13)
#6      _RemoteRunner._run (dart:isolate:1021:47)
#7      _RemoteRunner._remoteExecute (dart:isolate:1015:12)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:17)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
IO  : Writing 7377 characters to text file C:\Users\luca\AppData\Local\Pub\Cache\log\pub_log.txt.
MSG : Logs written to C:\Users\luca\AppData\Local\Pub\Cache\log\pub_log.txt.<br />
<br />
Note that removing logo_icon from pubspec.yaml solves problem.

### :scroll: Pubspec.yaml

name: test_project
description: Test project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.1.0
  dio: ^4.0.6
  decimal: ^2.3.1
  event: ^2.1.2
  intl: ^0.18.0
  loading_overlay: ^0.3.0
  path: ^1.8.2
  package_info_plus: ^4.0.2
  permission_handler: ^10.1.0
  presentation_displays: ^0.2.3
  provider: ^6.0.2
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.7
  window_manager: ^0.3.1
  wakelock_plus: ^1.1.1

msix_config:
  display_name: test_project
  publisher_display_name: Trend Servizi Srl
  identity_name: trendservizi.test.app
  msix_version: 1.60.7.0
  certificate_path: xxxxxxxxxxxx
  certificate_password: xxxxxxxxx
  publisher: CN=xxx, O=xxxxxx, S=xxxxx, C=xx
  logo_path: C:\users\luca\development\t3_fe\msix\logo2.png
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,privateNetworkClientServer,documentsLibrary,broadFileSystemAccess,location,microphone,webcam,runFullTrust'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/textures/

dev_dependencies:
  flutter_lints: ^2.0.1
  msix: ^3.16.2

**Comment by LucaBoss74** [comment]
I've already tried to change ".png" logo to another format (eg: JPG, TIF) without success. Tried also with another icon, same result.

**Comment by YehudaKremer** [comment]
Hello 

Thank you for the report,
i publish new version (3.16.3) of the MSIX package with temporary fix (fix the Image package dependency version on 4.1.0).

**Comment by YehudaKremer** [comment]
Permanent fix in version 3.16.4.

**Comment by LucaBoss74** [comment]
Thank you for your prompt answer and fix.Ing. Luca Lazzeroni - Responsabile Sviluppo Software Trend Servizi SrlIl 26 set 2023 07:20, Yehuda Kremer ***@***.***> ha scritto:
Permanent fix in version 3.16.4.
