### ISSUE TITLE
Unhandled exception: PathNotFoundException: Directory listing failed

### ISSUE THREAD

**Issue by xenSlayer** [YehudaKremer/msix#238]
### :information_source: Info

**Version: `^3.16.4`**

### :speech_balloon: Description

PathNotFoundException: Directory listing failed, path = 'C:\Users\xxx\Desktop\xxx\packages\xxx\build\windows\runner\Release\Images\*' (OS Error: The system cannot find the path specified.
, errno = 3)

**Enter a description of your problem here.<br />
Got this error when I set logo_path with relative file path.

### :scroll: Pubspec.yaml

msix_config:
  display_name: hello
  publisher_display_name: myapp
  identity_name: app.myapp.app
  languages: en-us
  enable_at_startup: true
  capabilities: "internetClient"
  logo_path: ./resources/icons/logo.png
  app_installer:
    automatic_background_task: true
    show_prompt: true
    output_name: xenmusic_installer

**Comment by banool** [comment]
I get this error too, even if I make the path absolute.

**Comment by banool** [comment]
@xenSlayer did you manage to fix this somehow?

**Comment by xenSlayer** [comment]
no not really.

**Comment by apoleo88** [comment]
I have the same issue

**Comment by ttzein6** [comment]
![image](https://github.com/YehudaKremer/msix/assets/72082671/b311d655-bcef-4b8a-90d5-d67f038882e0)
here is an example
