### ISSUE TITLE
[BUG] Missing DLL files

### ISSUE THREAD

**Issue by BikeBr0** [YehudaKremer/msix#262]
### :information_source: Info

**Version: `v3.16.7`**

### :speech_balloon: Description

Running the .msix installer on other Windows PCs fails with 4 missing DLL files:

- MSVCP140.dll
- vccorlib140.dll
- VCRUNTIME140_1.dll
- VCRUNTIME140.dll

Is this a bug in this plugin or do I need to manually configure these DLLs to be included in the package?

### :scroll: Pubspec.yaml

msix_config:
  display_name: My Apps Display Name
  logo_path: images/logo.png
  msix_version: 1.0.0.0
  signtool_options: /fd sha256 /sha1 --FINGERPRINT-- /tr http://timestamp.digicert.com

**Comment by BikeBr0** [comment]
I tried troubleshooting the problem by first running `dart run msix:build` and then `dart run msix:pack`. Interestingly, I saw that MSVCP140.dll, VCRUNTIME140_1.dll, and VCRUNTIME140.dll were in the Release folder after build but disappeared after pack. There are some other DLLs (like msvcp140_1.dll and msvcp140_2.dll) remaining in the Release folder however.

**Comment by BikeBr0** [comment]
I will close this issue as it seems that a particular plugin was causing this issue.

**Comment by NashIlli** [comment]
@BikeBr0 how did you solve this? Im having this issue.

**Comment by BikeBr0** [comment]
@NashIlli - [win_ble](https://github.com/rohitsangwan01/win_ble) was causing the problem. I switched to [universal ble](https://github.com/Navideck/universal_ble) and it started working.
