### ISSUE TITLE
runFullTrust configuration

### ISSUE THREAD

**Issue by muhsintr** [YehudaKremer/msix#264]
### :speech_balloon: Description
There is a restriction when uploading the MSIX file to Microsoft Store saying runFullTrust is requested and demands a description to be shown to users and requires approval. It would be great if an option would be added to cover it. There may be some impossibility due to win32 nature of Flutter Windows builds. I'm not sure about it. As I saw in source codes the "runFullTrust" capability will be added in any condition to the MSIX config file. The first idea is to remove it by an option.

### :question: Platform
Windows

**Comment by YehudaKremer** [comment]
https://github.com/YehudaKremer/msix/issues/110

**Comment by mln0007** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      
      <supportedOS Id="{8e0f7***-****-****-*****-***d50a15a9a}"/>
      
      <supportedOS Id="{1f676***-****-****-****-***0f6d0da78}"/>
      
      <supportedOS Id="{4a2f2***-****-****-****_***d4a4a6e38}"/>
      
      <supportedOS Id="{35138***-****-****-****-***40225f93a}"/>
    </application>
  </compatibility>
</assembly>    

This is my runner.exe.manifest file so where in the file should I add capabilities? And how to add (if description to be added)
