### ISSUE TITLE
[BUG] msvcp140.dll crashes and closes the app on windows 11 when playing sound

### ISSUE THREAD

**Issue by Hamid313-coder** [YehudaKremer/msix#272]
When I build my flutter windows app which has "audio_players" and "video_player" on windows 11 using msix, it crashes and closes the app when I play sound or play video.
I checked using "Event Viewer". it says the fault is from msvcp140.dll file.
when I replace that .dll file with file which is located in  "visual studio" folder. it works fine.

**Comment by insertjokehere** [comment]
This issue has eaten the last four days of my life, so bare with me if this explanation takes a bit.

1. When building a VC++ app (like all Flutter apps) you need to link against the VC++ runtime, and you include a version of the libraries with your app when you distribute it to end users
2. Microsoft [requires](https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170) that "the Redistributable version must be at least as new as the latest toolset used by any app component" 
3. This library [includes](https://github.com/YehudaKremer/msix/tree/main/lib/assets/VCLibs/x64) an ancient version of the VC++ runtime, and bundles them into the generated installer:

https://github.com/YehudaKremer/msix/blob/2faab7e8de473fc8e30a0a2a92b3dcc6a06a65c7/lib/src/assets.dart#L263-L270

4. Somehow, this has been working without major issues for the last few years - except that recently, Microsoft [released](https://github.com/microsoft/STL/wiki/Changelog#vs-2022-1710) an update to Visual Studio 2022 that fixed an issue in `mutex` from the VC++ runtime, but which requires that you follow the "at least as new as the latest toolset" rule. They even note in the changelog that

> Programs that aren't following the documented [restrictions on binary compatibility](https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170) may encounter null dereferences in mutex machinery"

5. Github have updated their `windows` and `windows-latest` runner images to use the newest Visual Studio, which has caused a bit of chaos generally: https://github.com/actions/runner-images/issues/10004

6. The upshot of this is that if any of the Flutter plugins you are using use `mutex`, _and_ you are building the app on a machine that has VS2022 17.10 or newer, _and_ your users don't already have VC++ runtime 14.40.33810.0 or newer, your app will crash as soon as the plugin tries to use the mutex

As far as fixes are concerned, I'm not sure the best approach here. The current approach of bundling an static version of the VC++ redist with this module is fundamentally broken, but I acknowledge that we need some kind of fix to make it easier to bundle the required libraries with the installer. 

I'm still working through a proper fix for my app, and will report back once I have one.

**Comment by insertjokehere** [comment]
OK - I have a workaround that Works For Me:

* https://github.com/insertjokehere/msix/tree/msvc_redist removes the logic from `msix` that includes the MSVC libraries
* https://github.com/insertjokehere/flutter_msvcredist copies the libraries that your app is linked against from the build environment so you get the correct versions.

I'll work on getting a proper PR up and getting my package onto pub.dev - for now, you'll need to use the packages from git. Update your pubspec like:

```yaml
dependencies:
  msvcredist:
    git:
      url: https://github.com/insertjokehere/flutter_msvcredist.git
      ref: main

dev_dependencies:
  msix:
    git:
      url: https://github.com/insertjokehere/msix.git
      ref: msvc_redist
```

**Comment by PeterNjeim** [comment]
Thank you for discovering the problem. I noticed that my local build worked fine but production build in GitHub Actions had the crash, and I analyzed the difference between the MSIX files and saw that they had a different DLL for a WebRTC plugin I use (which in an older version, immediately initiated an audio connection (still don't know why it gets a different DLL for it, but that's another issue)).

This made the app crash on startup, only in the production build lol. I also noticed that it had the old msvcp140.dll, vcruntime140.dll, and vcruntime140_1.dll. I noticed that replacing them with the new versions fixed it (or leaving them and instead changing the DLL of the WebRTC plugin). I was going to fix it by changing the DLL's manually, but I like the closure of knowing that it was audio specifically that was causing the issue

**Comment by UdaraAlwis** [comment]
> OK - I have a workaround that Works For Me:
> 
> * https://github.com/insertjokehere/msix/tree/msvc_redist removes the logic from `msix` that includes the MSVC libraries
> * https://github.com/insertjokehere/flutter_msvcredist copies the libraries that your app is linked against from the build environment so you get the correct versions.
> 
> I'll work on getting a proper PR up and getting my package onto pub.dev - for now, you'll need to use the packages from git. Update your pubspec like:
> 
> ```yaml
> dependencies:
>   msvcredist:
>     git:
>       url: https://github.com/insertjokehere/flutter_msvcredist.git
>       ref: main
> 
> dev_dependencies:
>   msix:
>     git:
>       url: https://github.com/insertjokehere/msix.git
>       ref: msvc_redist
> ```

Thank you for posting this workaround! We had a similar issue on Windows 11 where our Flutter Windows app crashing whenever we accessed the webcam through the [camera_windows ](https://pub.dev/packages/camera_windows) library. We're also using this [msix ](https://pub.dev/packages/msix) package for bundling our Windows app with flutter as well. 
This workaround helped us resolve that crash! I hope they release a permanent fix soon.

**Comment by venky9885** [comment]
Error find from Event Viewer
Faulting module name: MSVCP140.dll, version: 14.26.28804.1, time stamp: 0x5e9b29e5
Exception code: 0xc0000005

**Comment by YehudaKremer** [comment]
@riccardo-lomazzi  fix it https://github.com/YehudaKremer/msix/pull/273 (version [3.16.8](https://pub.dev/packages/msix/versions/3.16.8))
sorry for the late response.
