### ISSUE TITLE
[BUG] Protocol activation opens a new app instance instead of forwarding to a currently open app

### ISSUE THREAD

**Issue by chirag729** [YehudaKremer/msix#279]
### :information_source: Info

**Version: 3.16.8**

### :speech_balloon: Description

The app_links package now recommends this package to handle app opening from custom url schemes. I've switched over but I'm experiencing an issue where a new app instance is opened instead of the data being forwarded to the currently open instance. 

### :scroll: Pubspec.yaml

msix_config:
  name: Omnimind.Omnichess
  display_name: Omnichess - Chess Editor
  publisher: CN=A5F601E4-5DCE-4650-BA69-2ECC70BBEB3B
  publisher_display_name: Omnimind Ltd
  identity_name: Omnimind.Omnichess
  msix_version: 2.5.4.0
  capabilities: internetClient
  logo_path: resources\omnichess_app_icon.png
  store: true
  protocol_activation: omnichess

**Comment by YehudaKremer** [comment]
Hello

Search for "App instance flag to allow only one instance at a time." comment in this fike:
https://github.com/YehudaKremer/smart_watch_widget/blob/main/windows/runner/main.cpp

**Comment by chirag729** [comment]
@YehudaKremer Thanks for the speedy response
