### ISSUE TITLE
[FEATURE REQUEST] support multiple languages

### ISSUE THREAD

**Issue by sensuikan1973** [YehudaKremer/msix#35]
### :speech_balloon: Description
I want to support multiple languages.

Now, Language is fixed `en-US`.
https://github.com/YehudaKremer/msix/blob/1c84029270643fb57d7acdf8dd6c8242713b15c1/lib/src/msixFiles.dart#L142

So, when I upload `myapp.msix`, windows console says that your app support only `en-us` (in fact, my app also supports `ja-jp`).
![image](https://user-images.githubusercontent.com/23427957/112744997-e6f18900-8fdf-11eb-9a6e-5dbbbc64de03.png)

### :question: Platform
Windows

**Comment by sensuikan1973** [comment]
We can add supported language manually.
So, the priority of this issue is low, I think.

**Comment by YehudaKremer** [comment]
Hello @sensuikan1973 
i added configuration field for languages, so now the msix file should support multi languages.

see documentation: 
![image](https://user-images.githubusercontent.com/946652/112762360-ec62c980-9007-11eb-88be-ed5ad1f0fea0.png)

i publish new version to [Pub](https://pub.dev/packages/msix) with this addition: 1.0.4

please update if this help you,
thank you for this report

**Comment by sensuikan1973** [comment]
Thank you very much!
