### ISSUE TITLE
Version 2.0 Additional Features

### ISSUE THREAD

**Issue by YehudaKremer** [YehudaKremer/msix#37]
Hello,
i am writing here a list of features for version 2,
you welcome to add ideas and participate in improving this plugin 🛩️.

Version 2.0 Additional Features Planning:

- allow **all** configuration in the yaml file also as command line arguments (do it with one `List<String>` of fields names) - 👍https://github.com/YehudaKremer/msix/commit/8cdaef6b68c8f3d79ebc43ccd3b4bc19acc3a60a
- expose all the options for the Signtool cli as msix configuration [(Sign Tool documentation)](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe) - 👍https://github.com/YehudaKremer/msix/commit/faeb0f82cc6a7530f58dd60869e1857aceac25c0
- expose all the options for the MakeAppx cli as msix configuration [(MakeAppx documentation)](https://docs.microsoft.com/en-us/windows/msix/package/create-app-package-with-makeappx-tool) - 🚫 no significant cli additions
- ui: progress bar status when runing - 👍https://github.com/YehudaKremer/msix/commit/4e74a8c76cc79997708a34c07efec2758916d1e4
- shorten the long documentation - 👍https://github.com/YehudaKremer/msix/commit/b7cd53062dd78b7cafed302f7ff2020cc967d285
- Handle Protocol Activation and Redirection https://github.com/YehudaKremer/msix/issues/37#issuecomment-818728349 - 👍https://github.com/YehudaKremer/msix/commit/341f30bd8c79c0e03f84deeb2a368e440628e3f8

**Comment by del-sec** [comment]
I'm not sure if this isn't already covered by the first point, but the ability to add extensions (like [here](https://blog.magnusmontin.net/2019/05/10/handle-protocol-activation-and-redirection-in-packaged-apps/)) would be very useful.

**Comment by YehudaKremer** [comment]
> I'm not sure if this isn't already covered by the first point, but the ability to add extensions (like [here](https://blog.magnusmontin.net/2019/05/10/handle-protocol-activation-and-redirection-in-packaged-apps/)) would be very useful.

@del-sec very cool Feature, added here: https://github.com/YehudaKremer/msix/commit/341f30bd8c79c0e03f84deeb2a368e440628e3f8
thank you!

**Comment by YehudaKremer** [comment]
All Done 🎉 
msix 2.0.0 is now available on [pub.dev](https://pub.dev/packages/msix)

**Comment by richard457** [comment]
@YehudaKremer Thanks for this awesome plugin, for a beginner in windows app and certification, would be nice to have a step-by-step on how to get the app signed and published to the windows store this can help a lot.

**Comment by richard457** [comment]
Found this ```If you publish your msix to Windows Store you dont need to sign it, Windows Store does it for you. To generate msix file for Windows Store use the --store flag or add store: true in msix configuration sction in your pubspec.yaml.``` in documentation but I am not sure if adding store: true is what is needed to just upload the app to app store i.e not need to add this  # certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  # certificate_password: 1234 (require if using .pfx certificate)
