### ISSUE TITLE
[FEATURE REQUEST]  'Run as Admin' Problem

### ISSUE THREAD

**Issue by devon** [YehudaKremer/msix#40]
Got report when submitting to Windows Store, 

```
Unfortunately, the product does not work when ran without elevated permissions
```

There are two options related to this problem when using Inno Setup to build the package, but don't know how to config with MSIX:

```
[Setup]
PrivilegesRequired=lowest
DefaultDirName={userpf}\{#MyAppName}
```

userpf will install app to `{localappdata}`

Any tips?

**Comment by YehudaKremer** [comment]
hello @devon, sorry for the late respone 

this plugin give by default (as [recomented](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-manual-conversion#capabilities)) the "runFullTrust" capability,
the "**allowElevation**" is not added by default and you can add it in the "[capabilities](https://github.com/YehudaKremer/msix/blob/main/documentation/configuration.md)" config field (scroll down to the last field)

please update if the addition of this capability to the config help?
do you think it should be by default?

**Comment by devon** [comment]
I read the document here, https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

The documents suggest use runFullTrust, and not allowElevation for the app which submits to Microsoft Store.

Not sure the funFullTrust related to the 'Run as Admin' problem or not.

Or they reject the submits with the wrong information.

```
Unfortunately, the product does not work when run without elevated permissions Run as Admin.
```

We should keep the runFullTrust default config now.

**Comment by YehudaKremer** [comment]
can we close this @devon ?

**Comment by devon** [comment]
> can we close this @devon ?

I haven't taken the time to test the detail. We may close this ticket.
