### ISSUE TITLE
[BUG] Signing fails with error - NEW

### ISSUE THREAD

**Issue by chrisDK1977** [YehudaKremer/msix#50]
Creating the certificates as described in 

https://sahajrana.medium.com/how-to-generate-a-pfx-certificate-for-flutter-windows-msix-lib-a860cdcebb8

I get a certificate with this parameters

Certificate bag
Bag Attributes
    localKeyID: _XXX_
subject=C = DE, **ST = Berlin**, L = Berlin, O = COMPANY
issuer=C = DE, ST = Berlin, L = Berlin, O = COMPANY
-----BEGIN CERTIFICATE-----

and the following error and it seems "ST" is not valid...

how can I solve this problem?

...
```
'C=DE, ST=Berlin, L=Berlin, O=COMPANY' verstößt gegen pattern-Einschränkung von  '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Descr
iption|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*'.
Analyse des Attributs 'Publisher' mit dem Wert 'C=DE, ST=Berlin, L=Berlin, O=COMPANY' fehlgeschlagen.
Cleaning up output file ...
MakeAppx : error: Failure at (CreatePackage( overwrite, hashAlgorithm, fileList, outputPath, manifestStream.Get(), forceCompressionNone, performanceOptions, encryptPackage, encryptionOptions, cgmPath, mainPackagePathForResourceExemption, makepriExeFullPath)) - 0x80080204 - The specified package format is not va
lid: The package manifest is not valid.
MakeAppx : error: Package creation failed.
MakeAppx : error: 0x80080204 - The specified package format is not valid: The package manifest is not valid.
```

**Comment by YehudaKremer** [comment]
hello @chrisDK1977 

can you try without the 'ST' ?
btw do you have and put the 'CN' of your certificate ?

**Comment by chrisDK1977** [comment]
Hi YehudaKremer,

I don't know how. So that is what the OpenSSL-Tool is generating. Even using 
-subj /C=DE/S=Berlin/L=Berlin/O=COMPANY/CN=COMPANY
is not working as Openssl then says:
req: Skipping unknown subject name attribute "S"

**Comment by chrisDK1977** [comment]
When changing ST to S in the msix_config I get the error:

getting config values..  [√]
validate config values..  [√]
cleaning temporary files..  [√]
create icons folder..  [√]
copy icons..  [√]
create manifest file..  [√]
copy VCLibs files..  [√]
packing..  [√]
signing..  Done Adding Additional Store
Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)

SignTool Error: An unexpected internal error has occurred.

**Comment by YehudaKremer** [comment]
i publish new version ([2.4.0](https://pub.dev/packages/msix)) that automatically sign the .msix file for you,
also update the documentation.
