### ISSUE TITLE
Flutter dekstop release blank screen 

### ISSUE THREAD

**Issue by tonyhart7** [YehudaKremer/msix#52]
### :information_source: Info
MSIX latest

ok I successfully install msix installer on other machine but its just show black screen 
I know this is happen when a missing depedency But idk what dll missing is

can someone elaborate about this ?

**Comment by YehudaKremer** [comment]
Hello @tonyhart7 

you can try fix `Junaid Rehmat` solution:
https://stackoverflow.com/questions/69127335/flutter-windows-desktop-app-gets-stuck-on-white-screen-after-msix-installation 
please don't forget to **like** his answer if its helped you

**Comment by tonyhart7** [comment]
fix this issue because flutter dsnt throw error in debug mode
