### ISSUE TITLE
internetClient capability not working

### ISSUE THREAD

**Issue by SomeoneAndNoone** [YehudaKremer/msix#55]
### :information_source: Info
Version: 2.3.0

### :speech_balloon: Description
I am using Dio package for network connection. The problem is it is working while I am debugging and the release version is working on my windows laptop(not sure why) however it hasn't worked on my colleague's and friend's. it is saying no connection. 

When I removed the capability and created .msix, the internet is still working for some reason. Here is the capability I used: 

msix_config:
  display_name: My App
  publisher_display_name: MyCompany
  identity_name: MyCompany.Desktop.MyApp
  msix_version: 1.0.0.0
  publisher: CN=MyCompany, O=MyCompany, L=London, S=London, C=GB
  logo_path: C:\personal_icon.png
  start_menu_icon_path: C:\personal_icon.png
  tile_icon_path: C:\personal_icon.png
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,bluetooth,radios'

**Comment by YehudaKremer** [comment]
Hello @SomeoneAndNoone 
Some of the capabilities are for declaration purposes only and do not actually affect the capabilities of the installed app,
you app should access the internet [even without](https://stackoverflow.com/a/20333882/4480046) the `internetClient` capability.

Maybe try check the error log when you getting "no connection"

**Comment by SomeoneAndNoone** [comment]
Hi @YehudaKremer  thank you for explaining. I examined the app. I found an open issue connectivity_plus package in which it shows no connection when connected to wifi. 


Thank you very much for informing about it as it has been really helpful for me!
