### ISSUE TITLE
.dart_tool/flutter_build/generated_main.dart(50,14): error G9EFD8EEC: Member not found: 'Msix.registerWith'.[BUG] 

### ISSUE THREAD

**Issue by jinfagang** [YehudaKremer/msix#63]
.dart_tool/flutter_build/generated_main.dart(50,14): error G9EFD8EEC: Member not found: 'Msix.registerWith'.

**Comment by YehudaKremer** [comment]
Hello @jinfagang 

I need more details to try help you with this problem,
here the [issue template](https://github.com/YehudaKremer/msix/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by YehudaKremer** [comment]
please see: #68
