### ISSUE TITLE
Is it possible to ensure that a runtime is installed using this package?

### ISSUE THREAD

**Issue by thegrxp** [YehudaKremer/msix#64]
I would like users to install WebView2 when installing my app.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Is it something we can do?

Anyway thank you for your work!

**Comment by YehudaKremer** [comment]
hello

Yes, you can use WebView2 in your flutter app, and use msix to install it.
you can use the [webview_windows](https://pub.dev/packages/webview_windows) package to add WebView2 to your app.

1. [install](https://pub.dev/packages/webview_windows/install) **webview_windows**
2. replace your `main.dart` content with this [example code](https://pub.dev/packages/webview_windows/example) 
3. test it... and then [install](https://pub.dev/packages/msix) the **msix** package and [create](https://pub.dev/packages/msix) msix installer

result:
![image](https://user-images.githubusercontent.com/946652/142271320-12a9fb97-4b44-4c94-bfac-bdf23c16cc06.png)

**Comment by thegrxp** [comment]
Thank you for the answer! 
I’m already using the webview_windows package, but Webview2 is not included in it, we have to install it separately

**Comment by YehudaKremer** [comment]
i see, let me check..

**Comment by YehudaKremer** [comment]
See [MSIX support for WebView2 is lacking at the moment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/883#issuecomment-773812364)

In the meantime, you can install it at runtime as describe in your [link](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment),
first check if WebView2 Runtime is already install, if not, install it (silently).

1. install dependencies:
```yaml
dependencies:
  ffi: ^1.1.2
  win32: ^2.3.0
```

2. [download](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) the WebView2 Runtime installer (click on "Get the Link") and save it in your project assets folder (lets say in "myAssets/MicrosoftEdgeWebview2Setup.exe")
3. update the msix configuration field `assets_directory_path` for example:
```yaml
msix_config:
  assets_directory_path: 'C:\Users\me\Desktop\flutter_again\myAssets'
```

4. in your project, create a file **webview_install.dart** with the code:
```dart
import 'dart:ffi';
import 'dart:io';
import 'package:ffi/ffi.dart';
import 'package:win32/win32.dart';

bool isWebView2RuntimeIsInstalled() {
  var webView2RuntimeRegKey =
      r'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}'
          .toNativeUtf16();
  var webView2RuntimeReg64Key =
      r'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}'
          .toNativeUtf16();
  final phKey = calloc<HANDLE>();

  var isInstalled = RegOpenKeyEx(HKEY_LOCAL_MACHINE, webView2RuntimeRegKey, 0, KEY_READ, phKey) ==
          ERROR_SUCCESS ||
      RegOpenKeyEx(HKEY_LOCAL_MACHINE, webView2RuntimeReg64Key, 0, KEY_READ, phKey) ==
          ERROR_SUCCESS;

  free(phKey);
  free(webView2RuntimeRegKey);
  free(webView2RuntimeReg64Key);

  return isInstalled;
}

Future installWebView2() async {
  await Process.run('myAssets/MicrosoftEdgeWebview2Setup.exe', ['/silent', '/install']); // remove '/silent' for interactable installation
}
```
5. in your code (at the very start), execute the code (and show some loading icon until its finish to install):
```dart
import 'webview_install.dart';

if (!isWebView2RuntimeIsInstalled()) {
     await installWebView2();
 }
```

btw, its recommended to add needed WebView capabilities in your msix configuration, for example:
```yaml
msix_config:
  assets_directory_path: 'C:\Users\me\Desktop\flutter_again\myAssets'
  capabilities: 'internetClient, internetClientServer, privateNetworkClientServer, enterpriseAuthentication, sharedUserCertificates, enterpriseCloudSSO, location, microphone, webcam'
```

**Comment by thegrxp** [comment]
Wow thank you so much for this detailed answer!
