### ISSUE TITLE
[FEATURE REQUEST] Support application shortcut

### ISSUE THREAD

**Issue by chenhl05** [YehudaKremer/msix#66]
### :speech_balloon: Description
Is it possible to create a application shortcut on Windows desktop?
This would be easier to find an application than in the Windows start bar.

### :question: Platform
Windows

**Comment by YehudaKremer** [comment]
Hello,

Msix installer [not support](https://techcommunity.microsoft.com/t5/msix-deployment/msixbundle-installation-does-not-create-a-shortcut-on-desktop/m-p/2195225/highlight/true#M810) desktop shortcuts

But you can create desktop shortcut file (.link) programmatically.
first check if the app is running for the first time, if so, create desktop shortcut.

1. download .lnk file: [MyAppName.zip](https://github.com/YehudaKremer/msix/files/7621015/MyAppName.zip)
2. edit the .lnk file name to what ever you want
3. right click on the .lnk file and open **properties**, edit the field **Target**: change the "...\[**flutter_again_2**].exe" to your app name (same value as `name:` from your pubspec.yaml), and save
4. create [assets folder](https://github.com/YehudaKremer/msix#file_folder-dll-files-and-assets-ffi-library) called "myAssets" in your project folder, and copy to it the .lnk file
5. use the latest version of msix package: `2.6.4` or later 
6. add to your `msix_config`: 
```yaml
  add_execution_alias: true
  assets_directory_path: 'C:\Users\me\Desktop\your_project_path\myAssets'
```
7. edit your `main.dart`:
```dart
Future<void> _moveLnkFileToDesktop() async {
  // "my_app_name" is the value of "name:" in your pubspec.yaml
  String myAppDataPath = '${Platform.environment['AppData']}\\my_app_name';

  try {
    var myAppDataDirectoryExists = await Directory(myAppDataPath).exists();

    //if myAppDataDirectoryExists is false then the app is running for the first time
    if (!myAppDataDirectoryExists) {
      await Directory(myAppDataPath).create();
      await File('${File(Platform.resolvedExecutable).parent.path}\\myAssets\\MyAppName.lnk')
          .copy('${Platform.environment['USERPROFILE']}\\desktop\\MyAppName.lnk');
    }
  } catch (e) {
    //log
  }
}

void main() {
  runApp(MyApp());
  _moveLnkFileToDesktop();
}
```
in this code update your app name and the .lnk file name 

And that is, this function will copy the .lnk file to the use desktop only the first time the app will open (usually after the msix is finish installing)

TA DA:
![image](https://user-images.githubusercontent.com/946652/143944264-ff8e2eb8-4a8c-4e1d-a050-9d5c675d24d8.png)

**Comment by chenhl05** [comment]
Thank you very much for the detailed instructions with the specific code!
I understand the principle of desktop shortcut implementation now.

**Comment by zezo357** [comment]
i cant  change the ink file
![image](https://user-images.githubusercontent.com/25157308/152881905-70b4230c-ecbb-49af-bb78-b7dc462f994a.png)

**Comment by IosefSaiegh** [comment]
@zezo357 I use another directory: "C:\Program Files\WindowsApps\myapp.example.app_1.0.0.0_x64__fxkeb4dgdm144\my_app_name.exe"

**Comment by zezo357** [comment]
Thanks.

**Comment by RaySnow** [comment]
> @zezo357 I use another directory: "C:\Program Files\WindowsApps\myapp.example.app_1.0.0.0_x64__fxkeb4dgdm144\my_app_name.exe"

Is this means everytime I update the app version number, I have to modify the .link file's target properties first ?
Is there a better way? No need to modify  .link files every time

**Comment by RaySnow** [comment]
> > @zezo357 I use another directory: "C:\Program Files\WindowsApps\myapp.example.app_1.0.0.0_x64__fxkeb4dgdm144\my_app_name.exe"
> 
> Is this means everytime I update the app version number, I have to modify the .link file's target properties first ? Is there a better way? No need to modify .link files every time

I got it，If you want use like “%localappdata%\Microsoft\WindowsApps\youAppName.exe”, you have to add Alias first for you App, add this code in your AppxManifest.xml after '</uap:VisualElements>':
'''  
      <Extensions>
          <uap3:Extension Category="windows.appExecutionAlias"
                  Executable="youAppName.exe"
                  EntryPoint="Windows.FullTrustApplication">
              <uap3:AppExecutionAlias>
                  <desktop:ExecutionAlias Alias="youAppName.exe" />
              </uap3:AppExecutionAlias>
          </uap3:Extension>
      </Extensions>
'''
microsoft document: https://learn.microsoft.com/zh-cn/windows/msix/psf/create-shortcut-with-script-package-support-framework

Thanks @YehudaKremer , It's very helpful.

**Comment by Prince2347X** [comment]
> I got it，If you want use like “%localappdata%\Microsoft\WindowsApps\youAppName.exe”, you have to add Alias first for you App, add this code in your AppxManifest.xml after '</uap:VisualElements>':

Where can I find the AppxManifest.xml? In the documentation (from the link you shared), it is showing UI of some MSIX packaging tool.
