### ISSUE TITLE
[BUG] MSIX installer with Flutter 2.8.0

### ISSUE THREAD

**Issue by tonyhart7** [YehudaKremer/msix#68]
MSIX Latest 2.6.3 - 2.6.5

.dart_tool/flutter_build/generated_main.dart(38,14): error G9EFD8EEC: Member not found: 'Msix.registerWith'. [C:\Development\flutter projects\arsyad bis\bus-ticket-system\build\windows\flutter\flutter_assemble.vcxproj]
.dart_tool/flutter_build/generated_main.dart:1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Development\flutter projects\arsyad bis\bus-ticket-system\build\windows\CMakeFiles\c65f6c3baf04baf5631eb4f9a9094ee1\flutter_windows.dll.rule;C:\Development\flutter projects\arsyad bis\bus-ticket-system\build\windows\CMakeFiles\52f3e30c4dfc32b6fb110b1cc00a56d0\flutter_assemble.rule' exited with code 1. [C:\Development\flutter projects\arsyad bis\bus-ticket-system\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.

I cant sign or install on release or debug mode on flutter latest version

Flutter 2.8.0

**Comment by YehudaKremer** [comment]
#63

**Comment by tonyhart7** [comment]
> #63

so is this fixed ?? what I can help

**Comment by YehudaKremer** [comment]
I need more details to try help you with this problem,
here the [issue template](https://github.com/YehudaKremer/msix/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by YehudaKremer** [comment]
did you execute `flutter build windows` successfully ?
when you getting this error ?

**Comment by tonyhart7** [comment]
> did you execute `flutter build windows` successfully ? when you getting this error ?

thats the problem, I cant even run my project

**Comment by tonyhart7** [comment]
> did you execute `flutter build windows` successfully ? when you getting this error ?

Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
.dart_tool/flutter_build/generated_main.dart(38,14): error G9EFD8EEC: Member not found: 'Msix.registerWith'. [C:\Development\flutter projects\arsyad bis\bus-ticket-system\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by YehudaKremer** [comment]
`flutter build windows` is not msix package command, its flutter command that create the .exe files.
Only after `flutter build windows`, you using msix package command `flutter pub run msix:create` to create the msix installer file:
![image](https://user-images.githubusercontent.com/946652/145456956-67397df9-c868-426f-b982-bd85c5aec0d1.png)

maybe try removing the msix package completely and try `flutter build windows` again, see if `msix` causes this error

**Comment by YehudaKremer** [comment]
by the way, you sing msix under `dependencies:`, or `dev_dependencies:` ?

**Comment by tonyhart7** [comment]
> by the way, you sing msix under `dependencies:`, or `dev_dependencies:` ?

msix on depedency

**Comment by YehudaKremer** [comment]
its need to be under `dev_dependencies:`

**Comment by YehudaKremer** [comment]
any success ?

**Comment by tonyhart7** [comment]
> any success ?

will try tomorrow 
already past my time to sleep

**Comment by tonyhart7** [comment]
> its need to be under `dev_dependencies:`

yeah its run hehe
