### ISSUE TITLE
[BUG] taskbar image too small

### ISSUE THREAD

**Issue by YehudaKremer** [YehudaKremer/msix#71]
I compare version 2.6.x vs 2.7.x and most of the icons looks the same,
but taskbar image shrines down:
![image](https://user-images.githubusercontent.com/946652/147809939-b6143827-b235-4a0f-ae47-84f989777e8b.png)

**Comment by tsinis** [comment]
Thanks! You might maybe want to [check my older files](https://github.com/tsinis/colors_ai/tree/c6f687213bc5b596eb3c1c2cf71ef1d6112cd03c/resources/windows/store_assets) (which I've created by myself), to compare. Anyways, it might be related to SVG's padding, in my specific case, so you should definitely check it on some default icons. Anyway, it's not a big deal for me, generated icons are in any case better than doing the same thing manually :)

**Comment by YehudaKremer** [comment]
hey:)

i publish new version ([2.8.0](https://pub.dev/packages/msix)) that solve the small icon problem,
and also trim the image so the transparent padding will not affect the icons size.

the .svg format is deprecated for now, but there are few more other format, please se the [CHANGELOG](https://github.com/YehudaKremer/msix/blob/main/CHANGELOG.md#280)

hope its will help, thank you 👍
