### ISSUE TITLE
[FEATURE REQUEST] Allow Debug version

### ISSUE THREAD

**Issue by azchohfi** [YehudaKremer/msix#75]
### :speech_balloon: Description
A clear and concise description of what you would like to be added to Msix.
There should be a way to configure the buildFilesFolder variable so we can use the Debug folder, instead of the Release folder, to make it easier to debug projects.

**Comment by YehudaKremer** [comment]
Hello @azchohfi 

Good suggestion.
I added in version [2.8.11](https://pub.dev/packages/msix) the option to use `--debug`, `--release` flags, or use `debug: true` configuration.

**Comment by azchohfi** [comment]
Awesome! This will help me a lot! I was manually building debug, copying the files to the release folder, to just run the pack command again with "no build". Thank you!
