### ISSUE TITLE
Where does the package saves certificate in development?

### ISSUE THREAD

**Issue by richard457** [YehudaKremer/msix#85]
I want to share the app to another dev but need to share the certificate file for him to be able to install and run the app.

**Comment by YehudaKremer** [comment]
Hello

this package comes with test certificate: [test_certificate.pfx](https://github.com/YehudaKremer/msix/tree/main/lib/assets),
and when executing, this package install it in the [Certificate Stores](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/certificate-stores) for development/testing purpose.

**Comment by YehudaKremer** [comment]
send him the certificate: https://github.com/YehudaKremer/msix/blob/main/lib/assets/test_certificate.pfx
then install it manually on his pc as "Trusted Root Certification"

**Comment by richard457** [comment]
It asks the password, what is the default password? @YehudaKremer

**Comment by richard457** [comment]
Thank you, by da way figured out that the default password is 1234 if anyone asks.
