### ISSUE TITLE
cannot install certificate

### ISSUE THREAD

**Issue by mayur-16** [YehudaKremer/msix#88]
am new to windows application developement. i used your package to bundle my exe file ...

when i tried to run this code

```
PS c:\src\flutter_project\> flutter build windows
PS c:\src\flutter_project\> flutter pub run msix:create
```

**am getting this error**

```
✓ packing
✓ cleaning temporary files
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 84% installing certificate..
to install the certificate "C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/msix-2.8.13/lib/assets/test_certificate.pfx" you need to "Run as administrator" once
pub finished with exit code -1
```

i dont know how to run that as adminstrator.. please help.

**Comment by YehudaKremer** [comment]
Hey

In version 3.0.0-dev.1 you dont need to run as administrator, do you want to try this version?

**Comment by mayur-16** [comment]
thank you so much. now am using 3.0.0-dev.1

**Comment by jinfagang** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/21303438/152761915-94f58ebb-56fa-4669-9607-140bf784b8d1.png">

can not run even installed certificate

**Comment by YehudaKremer** [comment]
hello @jinfagang 

do you using the 3.0.0-dev.1 version? and you got the output:
![image](https://user-images.githubusercontent.com/946652/152764490-e60bc675-361a-49a5-90b2-9db5cfc03888.png)

please share more details

**Comment by jinfagang** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/21303438/152765569-7ed79258-66ef-4faa-af36-989ab97fa1f7.png">
yes

**Comment by YehudaKremer** [comment]
even now its "Untrusted" when you trying to install?

try using the default test-certificate by deleting the `certificate_path` config,
is its still "Untrusted" when you trying to install?

**Comment by jinfagang** [comment]
@YehudaKremer I can not even build windows now.... after deleting build

**Comment by YehudaKremer** [comment]
please share more details (see: https://github.com/YehudaKremer/msix/issues/63#issuecomment-968933739)

1. full pubspec.yaml content (remove sensitive date)
2. run with `-v` (verbose) and paste here full log (remove sensitive date)
3. run "flutter doctor" paste here full log

thank you

**Comment by mayur-16** [comment]
> <img alt="image" width="489" src="https://user-images.githubusercontent.com/21303438/152761915-94f58ebb-56fa-4669-9607-140bf784b8d1.png">
> 
> can not run even installed certificate


i got the same issue..
so i followed [this](https://www.advancedinstaller.com/install-test-certificate-from-msix.html) step. then its working fine

**Comment by jinfagang** [comment]
@mayur-16 I am not test cert but myself generated one. I don't want all my users doing this step for installing my app.

**Comment by YehudaKremer** [comment]
@mayur-16 hey
in version 3.0.0-dev.1 you don't need to do this step
>so i followed [this](https://www.advancedinstaller.com/install-test-certificate-from-msix.html) step. then its working fine
