### ISSUE TITLE
[BUG] To install the test certificate run the command "flutter pub run msix:create" as administrator

### ISSUE THREAD

**Issue by jinfagang** [YehudaKremer/msix#89]
···
To install the test certificate run the command "flutter pub run msix:create" as administrator
···

It keep gives me this bug.

**Comment by YehudaKremer** [comment]
you can use the version `3.0.0-dev.1`

or you can run your IDE/terminal at Administrator
see: https://github.com/YehudaKremer/msix/issues/88#issuecomment-1031100088

**Comment by jinfagang** [comment]
no, I was use that version but not work

**Comment by YehudaKremer** [comment]
please try version 3.0.0
