### ISSUE TITLE
[BUG] Scroll speed is significantly lower in the msix version than in the built exe

### ISSUE THREAD

**Issue by machiato32** [YehudaKremer/msix#92]
### :information_source: Info
Version: `v2.8.16`

### :speech_balloon: Description

If I open the installed app on Windows 11 and try to scroll with the touchpad the scrolling is way to slow, if I scroll with a mouse scroll wheel it's okay.
If I start the .exe file build with flutter build, the scroll speed is just fine with the touchpad as well as a mouse.

### :scroll: Pubspec.yaml

[pubspec.yaml](https://github.com/YehudaKremer/msix/files/8016434/pubspec.txt)

**Comment by YehudaKremer** [comment]
Hello

This package not addressing any functional of the app itself.
Maybe after installing, the windows touch settings take effect.. you try changing the touch settings to see its true
