### ISSUE TITLE
[BUG] running "flutter build windows" command 

### ISSUE THREAD

**Issue by zezo357** [YehudaKremer/msix#96]
### :information_source: Info

Version: `3.0.0-dev.3`

### :speech_balloon: Description

the installer runs flutter build windows then builds the msix file

i want to run the flutter pub run msix:create by it self since i include some dlls missing when building 

my process
build windows
add dlls 
create the msix

**Comment by YehudaKremer** [comment]
Hello

You can add them to the build folder, and then run `flutter pub run msix:create`,
those dll files will include in the msix installer

**Comment by YehudaKremer** [comment]
Or even better, use the formal method: [Adding assets and images(https://docs.flutter.dev/development/ui/assets-and-images)

**Comment by zezo357** [comment]
the dll files are for a package so i cant include them like that sadly

**Comment by zezo357** [comment]
> Hello
> 
> You can add them to the build folder, and then run `flutter pub run msix:create`, those dll files will include in the msix installer

i did try that 

but when build windows is called the dll gets overwritten

**Comment by YehudaKremer** [comment]
the `build windows` command overrides only the "data" folder and the .exe file,
its not deleting anything else

**Comment by zezo357** [comment]
> the `build windows` command overrides only the "data" folder and the .exe file, its not deleting anything else

the dll are for a package 

so the package when the app builds again overwrites the dlls i put there (since i am just using a newer version of the package dlls)

**Comment by zezo357** [comment]
the ones the package uses
![image](https://user-images.githubusercontent.com/25157308/153089192-4794067f-3e0a-4a0b-864c-190f34834585.png)
the ones that i want to use (since there is a problem with  ssl certificate)
![image](https://user-images.githubusercontent.com/25157308/153089354-7f5b8526-54c9-44fa-9da9-b43022e7de92.png)

**Comment by YehudaKremer** [comment]
Hello @zezo357 

I added in version [3.0.0-dev.4](https://pub.dev/packages/msix/versions/3.0.0-dev.4) the option `build_windows : false` so the command `msix:create` will not run the command `flutter build windows` internally.

**Comment by zezo357** [comment]
thanks now with the flag the files are as excepted
