### ISSUE TITLE
[BUG] Error public app Microsoft Store

### ISSUE THREAD

**Issue by JoseDiaz2211** [YehudaKremer/msix#99]
### :information_source: Info

Version: `e.g. v0.7.5`
2.8.18
### :speech_balloon: Description

Error public store

Enter a description of your problem here. <br />
Any logs, error and assets you have that can help to find this bug.

invalid identity name ("identity_name"): "55371JMDSOFTWARESRL.ContaCloudJD_25xda2h4j032t". need to be a string between 3 and 50 characters in length that consists of alpha-numeric, period, and dash characters.
pub finished with exit code -1

I'm given it to me by the microsoft store

You must upload at least one package. If you are using market groups, then each market group must have at least one package.

You must fix all package validation errors before submitting.

contacloundjd.msix16.7 MB
Invalid package family name: 55371JMDSOFTWARESRL.ContaCloudJD_fxkeb4dgdm144 (expected: 55371JMDSOFTWARESRL.ContaCloudJD_25xda2h4j032t)

Invalid package publisher name: CN=Msix Testing, O=Msix Testing Corporation, S=Some-State, C=US (expected: CN=71C7788D-8364-4DE1-ACE0-0CE3103A6C0D)

### :scroll: Pubspec.yaml

My Config
msix_config:
  identity_name: 55371JMDSOFTWARESRL.ContaCloudJD_25xda2h4j032t #ContaCloudJD #ContaCloudJD.ContaCloudJD.MyApp
  publisher: CN=71C7788D-8364-4DE1-ACE0-0CE3103A6C0D
  publisher_display_name: JMDSOFTWARE SRL
  display_name: ContaCloudJD
  msix_version: 9.95.3.0
  capabilities: "internetClient"
  logo_path: assets/logo.png #C:\<PathToIcon>\<Logo.png>
  # store: true

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

**Comment by YehudaKremer** [comment]
Hello @JoseDiaz2211 

"\_" is invalid in the 'identity_name' : 55371JMDSOFTWARESRL.ContaCloudJD_25xda2h4j032t

You can find your `publisher_display_name`, `identity_name` and `publisher` in Microsoft Store dashboard, looks something like this:
![image](https://user-images.githubusercontent.com/946652/153720317-b6424f52-2052-4496-95c0-a3fcd26574c2.png)
